### ISSUE TITLE
not able to edit any file in workspace while using https.

### ISSUE THREAD

**Issue by anshulcreative** [alkacon/opencms-core#184]
Hello all,

when i use a http url and try to edit any file in workspace, i am able to do.

But when i use https, i am not able to do.

i am using OpenCms 8.5.2
apache 2.2.22  
tomcat :: tomcat-7.0.42

below is the opencms.log :::::

12 Aug 2013 13:33:23,545 ERROR [ org.opencms.gwt.CmsGwtService: 286] 1376310803543
com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract com.alkacon.acacia.shared.ValidationResult org.opencms.ade.contenteditor.shared.rpc.I_CmsContentService.saveAndDeleteEntities(java.util.List,java.util.List,boolean) throws org.opencms.gwt.CmsRpcException' threw an unexpected exception: java.lang.NumberFormatException: UUID has to be represented by the standard 36-char representation
	at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:389)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:579)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.opencms.gwt.CmsGwtService.service(CmsGwtService.java:195)
	at org.opencms.main.OpenCmsCore.invokeGwtService(OpenCmsCore.java:1604)
	at org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:150)
	at org.opencms.main.OpenCmsServlet.doPost(OpenCmsServlet.java:167)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.NumberFormatException: UUID has to be represented by the standard 36-char representation
	at org.safehaus.uuid.UUID.<init>(Unknown Source)
	at org.opencms.util.CmsUUID.<init>(CmsUUID.java:124)
	at org.opencms.ade.contenteditor.shared.CmsContentDefinition.entityIdToUuid(CmsContentDefinition.java:167)
	at org.opencms.ade.contenteditor.CmsContentService.saveAndDeleteEntities(CmsContentService.java:326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561)
	... 27 more

Please help me to fix this issue.

Thanks,
Ansh

**Comment by aKandzior** [comment]
Should be fixed since 9.5.
