### ISSUE TITLE
External Link Validation fails on unpublished ressources

### ISSUE THREAD

**Issue by frittinger** [alkacon/opencms-core#287]
The external link validation (Administration View >  Link Validation >  External Link Validation >  Validate External Links) fails with an exception if it encounters a resource that is unpublished, i.e. a resource that is expired and exists only in the offline project. 
It looks like this exception is not adequately caught. I think it would be sufficient to catch this exception and proceed with the checking process.

Exception org.opencms.file.CmsVfsResourceNotFoundException: Error reading resource from path "/de/corporate/career/team".
at org.opencms.file.CmsVfsResourceNotFoundException.createException(CmsVfsResourceNotFoundException.java:71)
at org.opencms.db.CmsDbContext.throwException(CmsDbContext.java:334)
at org.opencms.db.CmsDbContext.report(CmsDbContext.java:286)
at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:4900)
at org.opencms.file.CmsObject.readResource(CmsObject.java:2957)
at org.opencms.file.CmsObject.readFile(CmsObject.java:2371)
at org.opencms.file.CmsObject.readFile(CmsObject.java:2342)
at org.opencms.relations.CmsExternalLinksValidator.validateLinks(CmsExternalLinksValidator.java:152)
at org.opencms.workplace.threads.CmsExternalLinksValidatorThread.run(CmsExternalLinksValidatorThread.java:89)
Caused by: org.opencms.file.CmsVfsResourceNotFoundException: Resource "/de/corporate/career/team" was not found.
at org.opencms.db.CmsSecurityManager.checkPermissions(CmsSecurityManager.java:6842)
at org.opencms.db.CmsSecurityManager.checkPermissions(CmsSecurityManager.java:6817)
at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:7244)
at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:4898)
... 5 more

Regards,
Frank Rittinger

**Comment by gWestenberger** [comment]
Fixed in upcoming release.
