### ISSUE TITLE
startup tomcat exception (opencms 9.5.0) 

### ISSUE THREAD

**Issue by superc** [alkacon/opencms-core#290]
```
Exception in thread "CmsSpellcheckingModuleIndexingThread" java.lang.OutOfMemory
Error: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:2786)
        at java.lang.StringCoding.safeTrim(StringCoding.java:64)
        at java.lang.StringCoding.access$300(StringCoding.java:34)
        at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:251)
        at java.lang.StringCoding.encode(StringCoding.java:272)
        at java.lang.String.getBytes(String.java:946)
        at org.apache.solr.common.util.ContentStreamBase$StringStream.getStream(
ContentStreamBase.java:169)
        at org.apache.solr.handler.loader.XMLLoader.load(XMLLoader.java:161)
        at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHand
ler.java:92)
        at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(Co
ntentStreamHandlerBase.java:74)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandl
erBase.java:135)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:1816)
        at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(Embe
ddedSolrServer.java:150)
        at org.apache.solr.client.solrj.request.AbstractUpdateRequest.process(Ab
stractUpdateRequest.java:117)
        at org.apache.solr.client.solrj.SolrServer.add(SolrServer.java:68)
        at org.apache.solr.client.solrj.SolrServer.add(SolrServer.java:54)
        at org.opencms.search.solr.spellchecking.CmsSpellcheckDictionaryIndexer.
addDocuments(CmsSpellcheckDictionaryIndexer.java:272)
        at org.opencms.search.solr.spellchecking.CmsSpellcheckDictionaryIndexer.
readAndAddDocumentsFromStream(CmsSpellcheckDictionaryIndexer.java:459)
        at org.opencms.search.solr.spellchecking.CmsSpellcheckDictionaryIndexer.
parseAndAddZippedDictionaries(CmsSpellcheckDictionaryIndexer.java:209)
        at org.opencms.search.solr.spellchecking.CmsSolrSpellchecker.parseAndAdd
Dictionaries(CmsSolrSpellchecker.java:222)
        at org.opencms.search.solr.spellchecking.CmsSpellcheckingModuleAction$1.
run(CmsSpellcheckingModuleAction.java:87)
        at java.lang.Thread.run(Thread.java:662)


Starting OpenCms, version 9.5.0 in web application "opencms"

Copyright (c) 2014 Alkacon Software GmbH
OpenCms comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to
redistribute it under certain conditions.
Please see the GNU Lesser General Public Licence for
further details.


Not starting JLAN server because no config file was found at D:\apache-tomcat-7.
0.50\webapps\opencms\WEB-INF\config\jlanConfig.xml
2014-11-8 13:18:03 com.sun.xml.ws.transport.http.servlet.WSServletContextListene
r contextInitialized
信息: WSSERVLET12: JAX-WS context listener initializing
Exception in thread "CmsSpellcheckingModuleIndexingThread" org.apache.solr.commo
n.SolrException: SolrCore 'spellcheck' is not available due to init failure: nul
l
        at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:1212)
        at org.opencms.search.CmsSearchManager.getSolrDictionary(CmsSearchManage
r.java:1467)
        at org.opencms.search.solr.spellchecking.CmsSpellcheckingModuleAction$1.
run(CmsSpellcheckingModuleAction.java:85)
        at java.lang.Thread.run(Thread.java:662)
Caused by: org.apache.solr.common.SolrException
        at org.apache.solr.core.SolrCore.<init>(SolrCore.java:821)
        at org.apache.solr.core.SolrCore.<init>(SolrCore.java:618)
        at org.apache.solr.core.CoreContainer.createFromLocal(CoreContainer.java
:949)
        at org.apache.solr.core.CoreContainer.create(CoreContainer.java:984)
        at org.apache.solr.core.CoreContainer$2.call(CoreContainer.java:597)
        at org.apache.solr.core.CoreContainer$2.call(CoreContainer.java:592)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:43
9)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExec
utor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:918)
        ... 1 more
Caused by: java.nio.channels.OverlappingFileLockException
        at sun.nio.ch.FileChannelImpl$SharedFileLockTable.checkList(FileChannelI
mpl.java:1166)
        at sun.nio.ch.FileChannelImpl$SharedFileLockTable.add(FileChannelImpl.ja
va:1068)
        at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:868)
        at java.nio.channels.FileChannel.tryLock(FileChannel.java:962)
        at org.apache.lucene.store.NativeFSLock.obtain(NativeFSLockFactory.java:
217)
        at org.apache.lucene.store.NativeFSLock.isLocked(NativeFSLockFactory.jav
a:319)
        at org.apache.lucene.index.IndexWriter.isLocked(IndexWriter.java:4094)
        at org.apache.solr.core.SolrCore.initIndex(SolrCore.java:473)
        at org.apache.solr.core.SolrCore.<init>(SolrCore.java:745)
        ... 13 more
2014-11-8 13:18:08 com.sun.xml.ws.transport.http.servlet.WSServletDelegate <init
>
信息: WSSERVLET14: JAX-WS servlet initializing
2014-11-8 13:18:08 org.apache.coyote.AbstractProtocol start
```

**Comment by aKandzior** [comment]
Closed as issue was resloved with a Tomcat update.
