### ISSUE TITLE
Error while clicking Sitemap Editor

### ISSUE THREAD

**Issue by ashishcsc** [alkacon/opencms-core#322]
When I trying to open sitemap editor, I am getting error message which says "The sitemap failed to load"

I cheked the log files which is as below.

29 Jun 2015 11:08:44,179 ERROR [ org.opencms.gwt.CmsGwtService: 184] 
java.lang.NullPointerException
	at org.opencms.ade.sitemap.CmsVfsSitemapService.prefetch(CmsVfsSitemapService.java:690)
	at org.opencms.ade.sitemap.CmsVfsSitemapService.prefetch(CmsVfsSitemapService.java:297)
	at org.opencms.ade.sitemap.CmsSitemapActionElement.getSitemapData(CmsSitemapActionElement.java:117)
	at org.opencms.ade.sitemap.CmsSitemapActionElement.export(CmsSitemapActionElement.java:80)
	at org.opencms.ade.sitemap.CmsSitemapActionElement.exportAll(CmsSitemapActionElement.java:98)
	at org.apache.jsp.WEB_002dINF.jsp.offline.system.modules.org_opencms_ade_sitemap.pages.sitemap_jsp._jspService(sitemap_jsp.java:74)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:604)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:543)
	at org.opencms.flex.CmsFlexRequestDispatcher.includeExternal(CmsFlexRequestDispatcher.java:188)
	at org.opencms.flex.CmsFlexRequestDispatcher.include(CmsFlexRequestDispatcher.java:163)
	at org.opencms.loader.CmsJspLoader.service(CmsJspLoader.java:645)
	at org.opencms.flex.CmsFlexRequestDispatcher.includeInternalWithCache(CmsFlexRequestDispatcher.java:417)
	at org.opencms.flex.CmsFlexRequestDispatcher.include(CmsFlexRequestDispatcher.java:167)
	at org.opencms.loader.CmsJspLoader.dispatchJsp(CmsJspLoader.java:936)
	at org.opencms.loader.CmsJspLoader.load(CmsJspLoader.java:525)
	at org.opencms.loader.CmsResourceManager.loadResource(CmsResourceManager.java:1199)
	at org.opencms.main.OpenCmsCore.showResource(OpenCmsCore.java:1719)
	at org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:153)
	at org.opencms.main.OpenCmsServlet.doPost(OpenCmsServlet.java:166)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

Can you please help what is the issue?
OpenCMS 9.5.2 .

Thanks,
Ashish

**Comment by aKandzior** [comment]
Closed as the Sitemap Editor apparently works. You probably have a configuration issue, but this is not a support form.
