### ISSUE TITLE
Clean up inappropriate logs

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#352]
Following messages are logged during clean installation:

```
ERROR [encms.i18n.CmsVfsBundleManager: 246] Unknown resource type name "xmlvfsbundle" requested.
org.opencms.loader.CmsLoaderException: Unknown resource type name "xmlvfsbundle" requested.
	at org.opencms.loader.CmsResourceManager.getResourceType(CmsResourceManager.java:944)
	at org.opencms.i18n.CmsVfsBundleManager.reload(CmsVfsBundleManager.java:183)
	at org.opencms.i18n.CmsVfsBundleManager.<init>(CmsVfsBundleManager.java:134)
	at org.opencms.main.OpenCmsCore.initConfiguration(OpenCmsCore.java:1378)
	at org.opencms.main.OpenCmsCore.upgradeRunlevel(OpenCmsCore.java:1988)
	at org.opencms.main.CmsShell.<init>(CmsShell.java:528)
	at org.opencms.main.CmsShell.<init>(CmsShell.java:450)
	at org.opencms.setup.CmsSetupWorkplaceImportThread.run(CmsSetupWorkplaceImportThread.java:151)

ERROR [encms.i18n.CmsVfsBundleManager: 246] Unknown resource type name "propertyvfsbundle" requested.
org.opencms.loader.CmsLoaderException: Unknown resource type name "propertyvfsbundle" requested.
	at org.opencms.loader.CmsResourceManager.getResourceType(CmsResourceManager.java:944)
	at org.opencms.i18n.CmsVfsBundleManager.reload(CmsVfsBundleManager.java:195)
	at org.opencms.i18n.CmsVfsBundleManager.<init>(CmsVfsBundleManager.java:134)
	at org.opencms.main.OpenCmsCore.initConfiguration(OpenCmsCore.java:1378)
	at org.opencms.main.OpenCmsCore.upgradeRunlevel(OpenCmsCore.java:1988)
	at org.opencms.main.CmsShell.<init>(CmsShell.java:528)
	at org.opencms.main.CmsShell.<init>(CmsShell.java:450)
	at org.opencms.setup.CmsSetupWorkplaceImportThread.run(CmsSetupWorkplaceImportThread.java:151)

```

If these are in fact errors, they should be fixed. If not, the log level `ERROR` is inappropriate.

**Comment by tHerrmann** [comment]
At the time the exception is thrown, a required resource type is not available yet. The module defining this type will be imported during the setup. So, at this time during setup, the exception is to be expected and probably should not be logged as an error.
After the setup though, this should not happen and logging it to the error channel is the right thing to do.
So, it's nothing to worry about, but could be improved.

**Comment by gallardo** [comment]
It'd be nice to have the log level lowered. They distract and make smoke tests more complicated. Furthermore, they lowered the error awareness, rendering logs less useful.
But I admit that this is low priority (though probably very cheap to solve).

**Comment by aKandzior** [comment]
This can usually be fixed by importing the modules in the "right" order. Closing this issue, see explanation from @tHerrmann
