### ISSUE TITLE
NPE opening Quick launch

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#378]
Playing around with a fresh created Site, after adding a gallery the quick launch throws a NPE and cannot be opened any more. It doesn't seem to be reversible.

![npe-open-quick-launch](https://cloud.githubusercontent.com/assets/790448/14178750/527de000-f75c-11e5-8fe1-d14e2b98261f.png)

The server logged:
```
31 Mar 2016 16:14:22,921 ERROR [ org.opencms.gwt.CmsGwtService: 183] java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
	at org.opencms.gwt.CmsQuickLaunchProvider.getQuickLaunchData(CmsQuickLaunchProvider.java:164)
	at org.opencms.gwt.CmsVfsService.loadQuickLaunchItems(CmsVfsService.java:1016)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:643)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.opencms.gwt.CmsGwtService.service(CmsGwtService.java:194)
	at org.opencms.main.OpenCmsCore.invokeGwtService(OpenCmsCore.java:1701)
	at org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:156)
	at org.opencms.main.OpenCmsServlet.doPost(OpenCmsServlet.java:175)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:643)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:879)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:610)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1777)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.opencms.gwt.CmsQuickLaunchProvider.getQuickLaunchData(CmsQuickLaunchProvider.java:121)
	... 30 more
31 Mar 2016 16:14:22,954 ERROR [ org.opencms.gwt.CmsLogService:  66] Client LOG (Host 129.69.58.193, Address 129.69.58.193, Ticket 1459433662929): java.lang.NullPointerException
org.opencms.gwt.CmsQuickLaunchProvider.getQuickLaunchData(CmsQuickLaunchProvider.java:164)
org.opencms.gwt.CmsVfsService.loadQuickLaunchItems(CmsVfsService.java:1016)
sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:606)
com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
javax.servlet.http.HttpServlet.service(HttpServlet.java:643)
javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
org.opencms.gwt.CmsGwtService.service(CmsGwtService.java:194)
org.opencms.main.OpenCmsCore.invokeGwtService(OpenCmsCore.java:1701)
org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:156)
org.opencms.main.OpenCmsServlet.doPost(OpenCmsServlet.java:175)
javax.servlet.http.HttpServlet.service(HttpServlet.java:643)
javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:879)
org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:610)
org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1777)
java.lang.Thread.run(Thread.java:745)
```

**Comment by tHerrmann** [comment]
Hi Alberto,
if you go back to the page editor and open the sitemap editor again, does the problem still persist??

**Comment by gallardo** [comment]
Hi Tobias,
if I'm not wrong, the problem persisted. But it was a somehow contrived scenario that I cannot easily reproduce now. A Tomcat 6 and a not configured environment played also their role.

I just wanted to document it, as it looked relatively easy to fix. You can close the report if you deem appropriate, and let it be reopened in case someone see it again.

**Comment by tHerrmann** [comment]
Hi Alberto,
we will certainly make this more robust for future releases.
Thanks for your efforts.
