### ISSUE TITLE
CmsConfigurationReader throws errors for missing .formatters

### ISSUE THREAD

**Issue by frittinger** [alkacon/opencms-core#388]
CmsConfigurationReader in OpenCms 10 tries to read a ".formatters" resource for each .config found. For every .formatters which cannot be read an error and stacktrace are logged. Especially the modules (see example) have no such .formatters resource.

I think this is not a problem in itself but the logfiles are full of such messages and simply shutting off logging for reading resources is not a solution here ...

Example:

22 Apr 2016 14:52:51,950 [http-apr-8080-exec-10] INFO  org.opencms.ade.configuration.CmsConfigurationReader  - Found module configuration /system/modules/org.opencms.jsp.search/.config for module org.opencms.jsp.search
22 Apr 2016 14:52:51,950 [http-apr-8080-exec-10] INFO  org.opencms.ade.configuration.CmsConfigurationReader  - Parsing configuration /system/modules/org.opencms.jsp.search/.config
22 Apr 2016 14:52:51,962 [http-apr-8080-exec-10] WARN  org.opencms.ade.configuration.CmsConfigurationReader  - Error reading resource from path "/system/modules/org.opencms.jsp.search/.formatters".
org.opencms.file.CmsVfsResourceNotFoundException: Error reading resource from path "/system/modules/org.opencms.jsp.search/.formatters".
	at org.opencms.file.CmsVfsResourceNotFoundException.createException(CmsVfsResourceNotFoundException.java:71)
	at org.opencms.db.CmsDbContext.throwException(CmsDbContext.java:335)
	at org.opencms.db.jpa.CmsDbContext.report(CmsDbContext.java:124)
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:4978)
	at org.opencms.file.CmsObject.readResource(CmsObject.java:3129)
	at org.opencms.file.CmsObject.readResources(CmsObject.java:3185)
	at org.opencms.file.CmsObject.readResources(CmsObject.java:3166)
	at org.opencms.ade.configuration.CmsConfigurationReader.readLocalMacroFormatters(CmsConfigurationReader.java:796)
	at org.opencms.ade.configuration.CmsConfigurationReader.parseFormatterChangeSet(CmsConfigurationReader.java:746)
	at org.opencms.ade.configuration.CmsConfigurationReader.parseConfiguration(CmsConfigurationReader.java:399)
	at org.opencms.ade.configuration.CmsConfigurationReader.parseSitemapConfiguration(CmsConfigurationReader.java:641)
	at org.opencms.ade.configuration.CmsConfigurationReader.readModuleConfigurations(CmsConfigurationReader.java:659)
	at org.opencms.ade.configuration.CmsConfigurationCache.loadModuleConfiguration(CmsConfigurationCache.java:484)
	at org.opencms.ade.configuration.CmsConfigurationCache.readCompleteConfiguration(CmsConfigurationCache.java:326)
	at org.opencms.ade.configuration.CmsConfigurationCache.initialize(CmsConfigurationCache.java:248)
	at org.opencms.ade.configuration.CmsADEManager.initialize(CmsADEManager.java:862)
	at org.opencms.main.OpenCmsCore.getADEManager(OpenCmsCore.java:412)
	at org.opencms.main.OpenCms.getADEManager(OpenCms.java:180)
	at org.opencms.gwt.CmsCoreService.prefetch(CmsCoreService.java:1036)
	at org.opencms.main.CmsUIServlet$1.modifyBootstrapPage(CmsUIServlet.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
	at com.vaadin.server.VaadinSession.modifyBootstrapResponse(VaadinSession.java:856)
	at com.vaadin.server.BootstrapHandler.getBootstrapHtml(BootstrapHandler.java:299)
	at com.vaadin.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:268)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1409)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:364)
	at org.opencms.main.CmsUIServlet.service(CmsUIServlet.java:280)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2503)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.opencms.file.CmsVfsResourceNotFoundException: Unable to read resource "/system/modules/org.opencms.jsp.search/.formatters".
	at org.opencms.db.generic.CmsVfsDriver.readResource(CmsVfsDriver.java:2350)
	at org.opencms.db.CmsDriverManager.readResource(CmsDriverManager.java:7589)
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:7337)
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:4976)
	... 52 more

**Comment by tHerrmann** [comment]
The above commit should fix the issue. Will be included in the next release.
