### ISSUE TITLE
Cannot create complex slider

### ISSUE THREAD

**Issue by ColdanR** [alkacon/opencms-core#402]
Using the "Add Content" Dialog on a container page to add a new complex slider. The slider is displayed but cannot be edited and will disappear when the page is reloaded.

Used version: 10.0.1 (updated from 10.0.0)

**Following stacktrace is logged at creation:**
15-Jun-2016 12:49:44.318 SEVERE [http-nio-80-exec-6] org.apache.catalina.core.ApplicationContext.log OpenCmsServlet: Fehler beim Lesen der Ressource mit der ID 00000000-0000-0000-0000-000000000000.
 org.opencms.file.CmsVfsResourceNotFoundException: Fehler beim Lesen der Ressource mit der ID 00000000-0000-0000-0000-000000000000.
	at org.opencms.file.CmsVfsResourceNotFoundException.createException(CmsVfsResourceNotFoundException.java:71)
	at org.opencms.db.CmsDbContext.throwException(CmsDbContext.java:335)
	at org.opencms.db.CmsDbContext.report(CmsDbContext.java:287)
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:4934)
	at org.opencms.file.CmsObject.readResource(CmsObject.java:3037)
	at org.opencms.ade.containerpage.CmsContainerpageService.getContainerElementBeanToSave(CmsContainerpageService.java:1719)
	at org.opencms.ade.containerpage.CmsContainerpageService.getContainerBeanToSave(CmsContainerpageService.java:1667)
	at org.opencms.ade.containerpage.CmsContainerpageService.generateContainerPageForContainers(CmsContainerpageService.java:1569)
	at org.opencms.ade.containerpage.CmsContainerpageService.saveContainers(CmsContainerpageService.java:2342)
	at org.opencms.ade.containerpage.CmsContainerpageService.saveContainerpage(CmsContainerpageService.java:1095)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.opencms.gwt.CmsGwtService.service(CmsGwtService.java:194)
	at org.opencms.main.OpenCmsCore.invokeGwtService(OpenCmsCore.java:1702)
	at org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:158)
	at org.opencms.main.OpenCmsServlet.doPost(OpenCmsServlet.java:177)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.opencms.file.CmsVfsResourceNotFoundException: Kann die Ressource mit der ID "00000000-0000-0000-0000-000000000000" nicht lesen.
	at org.opencms.db.generic.CmsVfsDriver.readResource(CmsVfsDriver.java:2292)
	at org.opencms.db.CmsDriverManager.readResource(CmsDriverManager.java:7580)
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:7335)
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:4932)
	... 44 more

**Trying to edit the complex slider:**
15-Jun-2016 12:50:35.906 SEVERE [http-nio-80-exec-5] org.apache.catalina.core.ApplicationContext.log Exception while dispatching incoming RPC call
 com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.opencms.ade.containerpage.shared.CmsCreateElementData org.opencms.ade.containerpage.shared.rpc.I_CmsContainerpageService.checkCreateNewElement(org.opencms.util.CmsUUID,java.lang.String,java.lang.String,java.lang.String) throws org.opencms.gwt.CmsRpcException' threw an unexpected exception: java.lang.IllegalArgumentException: Das Muster für neue Dateinamen "/sites/default/.content/sliders/slx_(%number).xml" enthält kein Nummernmacro.
	at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.opencms.gwt.CmsGwtService.service(CmsGwtService.java:194)
	at org.opencms.main.OpenCmsCore.invokeGwtService(OpenCmsCore.java:1702)
	at org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:158)
	at org.opencms.main.OpenCmsServlet.doPost(OpenCmsServlet.java:177)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Das Muster für neue Dateinamen "/sites/default/.content/sliders/slx_(%number).xml" enthält kein Nummernmacro.
	at org.opencms.loader.CmsDefaultFileNameGenerator.getNewFileNameFromList(CmsDefaultFileNameGenerator.java:272)
	at org.opencms.loader.CmsDefaultFileNameGenerator.getNewFileName(CmsDefaultFileNameGenerator.java:224)
	at org.opencms.loader.CmsDefaultFileNameGenerator.getNewFileName(CmsDefaultFileNameGenerator.java:187)
	at org.opencms.ade.configuration.CmsResourceTypeConfig.createNewElement(CmsResourceTypeConfig.java:375)
	at org.opencms.ade.containerpage.CmsContainerpageService.createNewElement(CmsContainerpageService.java:613)
	at org.opencms.ade.containerpage.CmsContainerpageService.checkCreateNewElement(CmsContainerpageService.java:499)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	... 33 more

**Comment by aZahner** [comment]
This has already been fixed for the 10.0.1 Apollo template modules. As these modules are not updated automatically, the issue from the 10.0.0 versions of the modules still persist in your installation. To resolve it manually, edit the file /system/modules/org.opencms.apollo.template.extensions/.config and change both occurrences of "...(%number)" with "...%(number)", i.e. place the "%" in front of the bracket.
