### ISSUE TITLE
Setup: "Tables could not be created" (branch_10_5_x)

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#430]
After setting **mysql** as database and **different users** for the "Setup" and "OpenCms" database connections, OpenCms aborts installation with the `Tables could not be created!` error message.

Database setup:
![screenshot_2016-10-09_06-13-51](https://cloud.githubusercontent.com/assets/790448/19217884/012c38a0-8de8-11e6-938c-bc0038a3d4d0.png)
Error:
![screenshot_2016-10-09_06-18-29](https://cloud.githubusercontent.com/assets/790448/19217892/53b22c24-8de8-11e6-8248-e26e4bfab614.png)

```
Tables could not be created!
Error connecting to database using: "jdbc:mysql://localhost:3306/opencms".
-------------------------------------------
java.sql.SQLException: Access denied for user 'opencms'@'localhost' (using password: YES)
     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1078)
     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4190)
     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4122)
     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:927)
     at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1709)
     at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1252)
     at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2486)
     at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2519)
     at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2304)
     at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.java:834)
     at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection.java:47)
     at sun.reflect.GeneratedConstructorAccessor268.newInstance(Unknown Source)
     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
     at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
     at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:416)
     at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:346)
     at java.sql.DriverManager.getConnection(DriverManager.java:664)
     at java.sql.DriverManager.getConnection(DriverManager.java:247)
     at org.opencms.setup.CmsSetupDb.setConnection(CmsSetupDb.java:515)
     at org.opencms.setup.CmsSetupDb.setConnection(CmsSetupDb.java:488)
     at org.apache.jsp.setup.step_005f5_005fdatabase_005fcreation_jsp._jspService(step_005f5_005fdatabase_005fcreation_jsp.java:404)
     at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
     at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
     at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
     at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
     at org.opencms.main.OpenCmsUrlServletFilter.doFilter(OpenCmsUrlServletFilter.java:132)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
     at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
     at java.lang.Thread.run(Thread.java:745)
-------------------------------------------
Error parsing database setup SQL script in line: ) ENGINE = MYISAM CHARACTER SET UTF8;
-------------------------------------------
java.lang.NullPointerException
     at org.opencms.setup.CmsSetupDb.executeStatement(CmsSetupDb.java:756)
     at org.opencms.setup.CmsSetupDb.executeSql(CmsSetupDb.java:672)
     at org.opencms.setup.CmsSetupDb.executeSql(CmsSetupDb.java:735)
     at org.opencms.setup.CmsSetupDb.createTables(CmsSetupDb.java:228)
     at org.apache.jsp.setup.step_005f5_005fdatabase_005fcreation_jsp._jspService(step_005f5_005fdatabase_005fcreation_jsp.java:415)
     at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
     at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
     at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
     at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
     at org.opencms.main.OpenCmsUrlServletFilter.doFilter(OpenCmsUrlServletFilter.java:132)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
     at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
     at java.lang.Thread.run(Thread.java:745)
-
```

Using 

```
$ mysql --version
mysql  Ver 14.14 Distrib 5.6.30, for Linux (x86_64) using  EditLine wrapper
```

Package info:

```
Information for package mysql-community-server:
-----------------------------------------------
Repository: Main Update Repository
Name: mysql-community-server
Version: 5.6.30-16.2
Arch: x86_64
Vendor: openSUSE
Installed: Yes
Status: up-to-date
```

**Comment by gallardo** [comment]
To document my progress with this one and to justify why I'm abandoning the attempt of fixing it myself:

- [`create_db.sql`](https://github.com/alkacon/opencms-core/blob/branch_10_5_x/webapp/setup/database/mysql/create_db.sql) is missing a `CREATE USER '${user}' IDENTIFIED BY '${password}'` sql statement
- [`CmsSetupBean.java`](https://github.com/alkacon/opencms-core/blob/branch_10_5_x/src-setup/org/opencms/setup/CmsSetupBean.java#L2172) is skipping the replacement configuration for these `user` and `password` with the corresponding `dbWorkUser` and `dbWorkPwd`
- MySQL does seem to require a host configuration for the user, for whom there is no configuration option in the GUI (e.g.: the execution of `CREATE USER 'opencms' IDENTIFIED BY 'passw'` creates a user `'opencms'@'%'` that cannot be used to create a connection within the local host -- I cannot understand why, but I could work around the problem if creating a qualified user `'opencms'@'localhost'`). I can hardly imagine a proper setup without this "host" input filed (pushing it to the limit, the jdbc connection string could be parsed to extract the host...)

I don't know how many issues more could be waiting here...

**Comment by tHerrmann** [comment]
Have you tried running the setup with an already existing 'Connection-User'?
I don't think, that creating a new database user is intended here.

**Comment by gallardo** [comment]
Hi @tHerrmann. That is in fact the case: as the form requires a DB root user, I though that that root user would create the opencms user. I've been mislead by my biased intuition...

**Comment by gallardo** [comment]
(As a side note: a hint in the GUI "Have you forgotten to create the user" would be valuable)
