### ISSUE TITLE
Error when clicking "Site Management" in Administration view

### ISSUE THREAD

**Issue by prasad0101** [alkacon/opencms-core#447]
Dear Expert's,

Could you please help me 

When I am clicking on the "Site Management" in Administration view. I am getting the below error.

Error while filling the list "Configured Sites".
 Reason: An unexpected error happened, but no error message has been provided.
 Please check the error details or contact your system administrator. 

Error Details are as follows : 

org.opencms.main.CmsRuntimeException: Error while filling the list "Configured Sites".
	at org.opencms.workplace.list.A_CmsListDialog.fillList(A_CmsListDialog.java:909)
	at org.opencms.workplace.list.A_CmsListDialog.refreshList(A_CmsListDialog.java:647)
	at org.opencms.workplace.list.A_CmsListDialog.actionDialog(A_CmsListDialog.java:383)
	at org.opencms.workplace.list.A_CmsListDialog.displayDialog(A_CmsListDialog.java:430)
	at org.opencms.workplace.list.A_CmsListDialog.displayDialog(A_CmsListDialog.java:415)
	at org.apache.jsp.WEB_002dINF.jsp.offline.system.workplace.admin.sites.index_jsp._jspService(index_jsp.java:53)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:377)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:646)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:436)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:374)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:302)
	at org.opencms.flex.CmsFlexRequestDispatcher.forward(CmsFlexRequestDispatcher.java:111)
	at org.opencms.loader.CmsJspLoader.load(CmsJspLoader.java:522)
	at org.opencms.loader.CmsResourceManager.loadResource(CmsResourceManager.java:1193)
	at org.opencms.main.OpenCmsCore.showResource(OpenCmsCore.java:1719)
	at org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:153)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:646)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:436)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:374)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:302)
	at org.opencms.flex.CmsFlexRequestDispatcher.forward(CmsFlexRequestDispatcher.java:111)
	at org.opencms.util.CmsRequestUtil.forwardRequest(CmsRequestUtil.java:469)
	at org.opencms.workplace.tools.CmsToolManager.jspForwardPage(CmsToolManager.java:475)
	at org.opencms.workplace.administration.CmsAdminDialog.displayDialog(CmsAdminDialog.java:92)
	at org.apache.jsp.WEB_002dINF.jsp.offline.system.workplace.views.admin.admin_002dmain_jsp._jspService(admin_002dmain_jsp.java:57)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:377)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:646)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:436)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:374)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:302)
	at org.opencms.loader.CmsJspLoader.load(CmsJspLoader.java:522)
	at org.opencms.loader.CmsResourceManager.loadResource(CmsResourceManager.java:1193)
	at org.opencms.main.OpenCmsCore.showResource(OpenCmsCore.java:1719)
	at org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:153)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:299)
	at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
	at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
	at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:769)
	at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:698)
	at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:891)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.opencms.workplace.tools.sites.CmsSitesOverviewList.fillDetails(CmsSitesOverviewList.java:270)
	at org.opencms.workplace.list.A_CmsListDialog.initializeDetail(A_CmsListDialog.java:991)
	at org.opencms.workplace.list.A_CmsListDialog.fillList(A_CmsListDialog.java:906)
	... 68 more

**Comment by prasad0101** [comment]
Please help....

**Comment by aKandzior** [comment]
Unfortunately we cannot reproduce the issue with the amount of information provided. It's likely your issue is somewhere in your configuration, but his is not a bug but a support issue.
