### ISSUE TITLE
SQL error ?

### ISSUE THREAD

**Issue by twofisher** [alkacon/opencms-core#450]
Publishing resources ...
Updating JSP loader cache...
Updating file /localizationtool.jsp ... o.k.
.. JSP loader cache updated
Publishing files ...
( 1 / 1 ) Publishing file /localizationtool.jsp ... Error publishing file "/sites/default/localizationtool.jsp". 
Exception org.opencms.main.CmsRuntimeException: The SQL query "C_RELATIONS_DELETE_BROKEN_LOCALE_RELATIONS" could not be found.
at org.opencms.db.generic.CmsSqlManager.readQuery(CmsSqlManager.java:360)
at org.opencms.db.generic.CmsSqlManager.getPreparedStatement(CmsSqlManager.java:261)
at org.opencms.db.generic.CmsVfsDriver.updateBrokenRelations(CmsVfsDriver.java:4686)
at org.opencms.db.generic.CmsVfsDriver.deleteRelations(CmsVfsDriver.java:1206)
at org.opencms.db.generic.CmsVfsDriver.updateRelations(CmsVfsDriver.java:3071)
at org.opencms.db.generic.CmsProjectDriver.publishChangedFile(CmsProjectDriver.java:3520)
at org.opencms.db.generic.CmsProjectDriver.publishFile(CmsProjectDriver.java:1238)
at org.opencms.db.generic.CmsProjectDriver.publishProject(CmsProjectDriver.java:1812)
at org.opencms.db.CmsDriverManager.publishJob(CmsDriverManager.java:6088)
at org.opencms.publish.CmsPublishThread.run(CmsPublishThread.java:154)
Statistics: published files: 1, published folders: 0, deleted folders: 0, duration: 00:00:00
Exception org.opencms.main.CmsRuntimeException: Error publishing file "/sites/default/localizationtool.jsp". 
at org.opencms.main.CmsRuntimeException.createException(CmsRuntimeException.java:81)
at org.opencms.db.CmsDbContext.throwException(CmsDbContext.java:337)
at org.opencms.db.CmsDbContext.report(CmsDbContext.java:287)
at org.opencms.db.generic.CmsProjectDriver.publishProject(CmsProjectDriver.java:1849)
at org.opencms.db.CmsDriverManager.publishJob(CmsDriverManager.java:6088)
at org.opencms.publish.CmsPublishThread.run(CmsPublishThread.java:154)
Caused by: org.opencms.main.CmsRuntimeException: The SQL query "C_RELATIONS_DELETE_BROKEN_LOCALE_RELATIONS" could not be found.
at org.opencms.db.generic.CmsSqlManager.readQuery(CmsSqlManager.java:360)
at org.opencms.db.generic.CmsSqlManager.getPreparedStatement(CmsSqlManager.java:261)
at org.opencms.db.generic.CmsVfsDriver.updateBrokenRelations(CmsVfsDriver.java:4686)
at org.opencms.db.generic.CmsVfsDriver.deleteRelations(CmsVfsDriver.java:1206)
at org.opencms.db.generic.CmsVfsDriver.updateRelations(CmsVfsDriver.java:3071)
at org.opencms.db.generic.CmsProjectDriver.publishChangedFile(CmsProjectDriver.java:3520)
at org.opencms.db.generic.CmsProjectDriver.publishFile(CmsProjectDriver.java:1238)

![sql error](https://cloud.githubusercontent.com/assets/12093283/20292607/e5a912b0-ab29-11e6-8773-3e178ca61664.PNG)

**Comment by dSeidel** [comment]
Hi twofisher, you added an outdated query.properties with your chinese localization, that's why the query is missing. See PR #449 for details.

Best, Daniel.
