### ISSUE TITLE
OpenCms 10.0.1: CmsVfsResourceNotFoundException after editing and switching to /sites/shared/

### ISSUE THREAD

**Issue by kartobi** [alkacon/opencms-core#472]
![shared_shared](https://cloud.githubusercontent.com/assets/2276952/21886651/aeb6c988-d8b4-11e6-9cba-dd04c3c4116b.png)

I get it reproduced each time I do the following steps:
- Open a resource inside a **subfolder** of /sites/shared/ and edit it or change a property
- Switch to /sites/default/
- Switch back to /sites/shared/

**Stacktrace:**
Error reading resource from path "/shared/shared".
org.opencms.file.CmsVfsResourceNotFoundException: Error reading resource from path "/shared/shared".
	at org.opencms.file.CmsVfsResourceNotFoundException.createException(CmsVfsResourceNotFoundException.java:71)
	at org.opencms.db.CmsDbContext.throwException(CmsDbContext.java:335)
	at org.opencms.db.jpa.CmsDbContext.report(CmsDbContext.java:124)
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:4979)
	at org.opencms.file.CmsObject.readResource(CmsObject.java:3131)
	at org.opencms.ui.apps.CmsFileExplorer.readTreeLevel(CmsFileExplorer.java:1708)
	at org.opencms.ui.apps.CmsFileExplorer$TreeExpandListener.nodeExpand(CmsFileExplorer.java:451)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1008)
	at com.vaadin.ui.Tree.fireExpandEvent(Tree.java:1121)
	at com.vaadin.ui.Tree.expandItem(Tree.java:341)
	at com.vaadin.ui.Tree.expandItem(Tree.java:305)
	at org.opencms.ui.apps.CmsFileExplorer.openPath(CmsFileExplorer.java:1648)
	at org.opencms.ui.apps.CmsFileExplorer.changeSite(CmsFileExplorer.java:1010)
	at org.opencms.ui.apps.CmsFileExplorer.changeSite(CmsFileExplorer.java:994)
	at org.opencms.ui.apps.CmsFileExplorer$15.valueChange(CmsFileExplorer.java:1849)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1008)
	at com.vaadin.ui.AbstractField.fireValueChange(AbstractField.java:1159)
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:570)
	at com.vaadin.ui.AbstractSelect.setValue(AbstractSelect.java:729)
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:468)
	at com.vaadin.ui.ComboBox.changeVariables(ComboBox.java:730)
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:603)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:422)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:79)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1409)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:364)
	at org.opencms.main.CmsUIServlet.service(CmsUIServlet.java:280)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2503)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.opencms.file.CmsVfsResourceNotFoundException: Unable to read resource "/shared/shared".
	at org.opencms.db.generic.CmsVfsDriver.readResource(CmsVfsDriver.java:2350)
	at org.opencms.db.CmsDriverManager.readResource(CmsDriverManager.java:7609)
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:7363)
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:4977)
	... 61 more

**Comment by kartobi** [comment]
Why "invalid"? What could be the problem?

**Comment by tHerrmann** [comment]
Sorry about that, my comment got lost. We fixed this issue in release 10.5.0.

**Comment by kartobi** [comment]
Ok. Thx.
