### ISSUE TITLE
static export not working out-of-the-box

### ISSUE THREAD

**Issue by abarrigas** [alkacon/opencms-core#494]
After doing a clean install of Opencms 10.5.1 on Tomcat8+JDK1.8 or Tomcat7+JDK1.7 I can't do a site static export from "Database management" menu.
Non-template resources are exported correctly, but other resources throw error 500.

Tomcat localhost log shows these messages:

```
27-Apr-2017 03:17:26.387 SEVERE [http-nio-8080-exec-4] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet.service() for servlet OpenCmsServlet threw exception
 java.lang.NullPointerException
	at org.opencms.staticexport.CmsStaticExportManager.getExportData(CmsStaticExportManager.java:889)
	at org.opencms.main.OpenCmsServlet.handle(OpenCmsServlet.java:209)
	at org.opencms.main.OpenCmsServlet.invokeHandler(OpenCmsServlet.java:292)
	at org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:153)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.opencms.jsp.jsonpart.CmsJsonPartFilter.doFilter(CmsJsonPartFilter.java:281)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:716)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at org.opencms.main.OpenCmsUrlServletFilter.doFilter(OpenCmsUrlServletFilter.java:127)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1533)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1489)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

27-Apr-2017 03:17:26.387 SEVERE [http-nio-8080-exec-4] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet default threw exception
 java.lang.NullPointerException
	at org.opencms.staticexport.CmsStaticExportManager.getExportData(CmsStaticExportManager.java:889)
	at org.opencms.main.OpenCmsServlet.handle(OpenCmsServlet.java:209)
	at org.opencms.main.OpenCmsServlet.invokeHandler(OpenCmsServlet.java:292)
	at org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:153)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.opencms.jsp.jsonpart.CmsJsonPartFilter.doFilter(CmsJsonPartFilter.java:281)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:716)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at org.opencms.main.OpenCmsUrlServletFilter.doFilter(OpenCmsUrlServletFilter.java:127)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1533)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1489)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

I finally found a workaround:
1- Modify opencms/web.xml, and comment two sections:

From:
```
     <filter>
        <filter-name>OpenCmsUrlServletFilter</filter-name>
        <filter-class>org.opencms.main.OpenCmsUrlServletFilter</filter-class>
            <!--Use the init-param to prevent rewriting for URI that start with the provided prefixes-->
        <init-param>
            <param-name>additionalExcludePrefixes</param-name>
            <param-value>/my-servlet-1|/my-servlet-2</param-value>
        </init-param>
         
    </filter> 
    
    <filter>
        <filter-name>CmsJsonPartFilter</filter-name>
        <filter-class>org.opencms.jsp.jsonpart.CmsJsonPartFilter</filter-class>
    </filter>


   <filter-mapping>
        <filter-name>OpenCmsUrlServletFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
```
to

```
<!--<filter>
        <filter-name>OpenCmsUrlServletFilter</filter-name>
        <filter-class>org.opencms.main.OpenCmsUrlServletFilter</filter-class>
            Use the init-param to prevent rewriting for URI that start with the provided prefixes
        <init-param>
            <param-name>additionalExcludePrefixes</param-name>
            <param-value>/my-servlet-1|/my-servlet-2</param-value>
        </init-param>
         
    </filter> -->
    
    <filter>
        <filter-name>CmsJsonPartFilter</filter-name>
        <filter-class>org.opencms.jsp.jsonpart.CmsJsonPartFilter</filter-class>
    </filter>


<!--
   <filter-mapping>
        <filter-name>OpenCmsUrlServletFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping> 
-->
```

2- Modifiy opencms/conf/opencms-importexport.xml, adding SERVLET_NAME to vfs- prefix:

From
`<vfs-prefix>${CONTEXT_NAME}</vfs-prefix>`
to
`<vfs-prefix>${CONTEXT_NAME}${SERVLET_NAME}</vfs-prefix>`

After that I need to access opencms using ip:port/opencms/opencms/, but sites export correctly when export is set to true.

**Comment by rothemel** [comment]
I can confirm that it doesn't work after installation. I changed only the opencms-importexport.xml
original:
<exporturl>http://127.0.0.1:8080${CONTEXT_NAME}/handle404</exporturl>
to: 
<exporturl>http://127.0.0.1:8080${CONTEXT_NAME}</exporturl>

this works for me.

**Comment by tHerrmann** [comment]
Hi,
the standard configuration is aimed at dynamic web site delivery. To use a statically exported site, you have to make the change stated by @rothemel .
This should be better documented, but it works as intended.
