### ISSUE TITLE
OpenCmsShell: hangs on NPE

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#499]
In interactive mode, some improper commands result in NPE:
```
Admin@Offline:|/>^[[A
null 'A'
java.lang.NullPointerException
	at org.opencms.main.CmsShell$CmsCommandObject.buildMethodLookup(CmsShell.java:302)
	at org.opencms.main.CmsShell$CmsCommandObject.executeMethod(CmsShell.java:126)
	at org.opencms.main.CmsShell.executeCommand(CmsShell.java:1050)
	at org.opencms.main.CmsShell.execute(CmsShell.java:705)
	at org.opencms.main.CmsShell.execute(CmsShell.java:639)
	at org.opencms.main.CmsShell.main(CmsShell.java:617)
```
The Shell hangs and doesn't terminate.

Unfortunately, the `^[[A` is issued on <kbd>up</kbd> keypress, something that happens pretty frequently due to convulsive reflexes...

A Stacktrace shows some non-daemon threads and suggests that either some threads are created with inappropriate settings or that the shell is missing a correct shutdown process:

```
"OpenCms: Offline Search Indexer" #27 prio=5 os_prio=0 tid=0x00007f3facfd9800 nid=0x20e1 waiting on condition [0x00007f3f3c7e8000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.opencms.search.CmsSearchManager$CmsSearchOfflineIndexThread.run(CmsSearchManager.java:389)

"Thread-3" #22 prio=5 os_prio=0 tid=0x00007f3fad50d800 nid=0x20dc in Object.wait() [0x00007f3f3c6e7000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000005cbf33478> (a java.lang.Object)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.solr.core.CloserThread.run(CoreContainer.java:1250)
	- locked <0x00000005cbf33478> (a java.lang.Object)

"OpenCms: Scheduler" #15 prio=5 os_prio=0 tid=0x00007f3fad317800 nid=0x20d5 waiting on condition [0x00007f3f88366000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:394)


```

**Comment by gallardo** [comment]
With #500 fixed in 81b01cf12fc7f35757aef061741d4a1431f6865b, this will be hard to reproduce. I'm closing this and will reopen if needed.
