### ISSUE TITLE
Problem after deleting, inside the editor, all configured locales from a xml resource with more, 'hidden', locales

### ISSUE THREAD

**Issue by ggiudetti** [alkacon/opencms-core#513]
I've seen this problem after importing a resource from a system configured with more locales than the target system (10.5.1).
The source instance has these locales configured: 'it', 'en', 'zh', 'pt', 'de', 'ru'
The target instance has only 'it' and 'en'.
This happened to one of our users, but it is replicable.
She was editing an imported resource that had contents in 2 locales, 'it' and 'ru' ('ru' was not visible on the locale selectbox).
She managed to delete 'it' and a selectbox with 'ru' was now showing.
On this action, the following was logged:

`06 lug 2017 10:35:33,786 ERROR [ org.opencms.gwt.CmsLogService:  66] Client LOG (Host 127.0.0.1, Address 127.0.0.1, Ticket 1499330140521): (TypeError) : Cannot read property 'd' of undefined
Unknown.x8d(http://cms.visittuscany.com/handleStatic/v1448580201v/gwt/opencms/D88699043410CD9FD5834929D6E838CB.cache.html)
Unknown.sKe(http://cms.visittuscany.com/handleStatic/v1448580201v/gwt/opencms/D88699043410CD9FD5834929D6E838CB.cache.html)
Unknown.VGe(http://cms.visittuscany.com/handleStatic/v1448580201v/gwt/opencms/D88699043410CD9FD5834929D6E838CB.cache.html)
Unknown.iHe(http://cms.visittuscany.com/handleStatic/v1448580201v/gwt/opencms/D88699043410CD9FD5834929D6E838CB.cache.html)
Unknown.AIe(http://cms.visittuscany.com/handleStatic/v1448580201v/gwt/opencms/D88699043410CD9FD5834929D6E838CB.cache.html)
Unknown.CIe(http://cms.visittuscany.com/handleStatic/v1448580201v/gwt/opencms/D88699043410CD9FD5834929D6E838CB.cache.html)
Unknown.UIe(http://cms.visittuscany.com/handleStatic/v1448580201v/gwt/opencms/D88699043410CD9FD5834929D6E838CB.cache.html)
Unknown.R8e(http://cms.visittuscany.com/handleStatic/v1448580201v/gwt/opencms/D88699043410CD9FD5834929D6E838CB.cache.html)
Unknown.QIe(http://cms.visittuscany.com/handleStatic/v1448580201v/gwt/opencms/D88699043410CD9FD5834929D6E838CB.cache.html)
Unknown.SIe(http://cms.visittuscany.com/handleStatic/v1448580201v/gwt/opencms/D88699043410CD9FD5834929D6E838CB.cache.html)`

and the system became 'unstable', in the sense that the xml editors did not show the locale selectbox anymore and the site showed pages in one locale only.

This log started to appear too:
`06 lug 2017 10:39:02,091 ERROR [ org.opencms.gwt.CmsGwtService: 183] 
java.lang.NullPointerException
        at org.opencms.ade.contenteditor.CmsContentService.readContentDefinition(CmsContentService.java:1474)
        at org.opencms.ade.contenteditor.CmsContentService.loadInitialDefinition(CmsContentService.java:459)
        at sun.reflect.GeneratedMethodAccessor317.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at org.opencms.gwt.CmsGwtService.service(CmsGwtService.java:194)
`

This problem is only solved by restarting tomcat.

**Comment by tHerrmann** [comment]
Hi,
I can reproduce the issue. Current work around is, make sure to have all locales configured when importing contents. We will try to make the content editor more robust for future versions.

**Comment by tHerrmann** [comment]
This has been fixed in branch_10_5_x with commits e37b46e80526ece16bcbca9be8c704bf63fd286a and 89bab6a08f59cd9a132a8c8ccd88bcee48e00936.

**Comment by tHerrmann** [comment]
This has been fixed with release 10.5.4.
