### ISSUE TITLE
Error issues in opencms 10.5.2

### ISSUE THREAD

**Issue by superc** [alkacon/opencms-core#524]
windows7
apache-tomcat-8.5.20
jdk1.8.0_144
mysql5.1

Download and install opencms from "http://www.opencms.org/downloads/opencms/opencms-10.5.2.zip".
Restar tomcat and visit website.
No Blog articles list in "/opencms/apollo-demo/blog/articles/".
No resources in content elements types when "Add content" from toolbar,but explorer existing resources.

![blog articles list](https://user-images.githubusercontent.com/3608960/29664676-3fb1f170-8903-11e7-848b-3b3a35ee8019.png)

![toolbar](https://user-images.githubusercontent.com/3608960/29664677-3fc8d160-8903-11e7-8df0-0db99b75d09d.png)

opencms.log
```
24 Aug 2017 19:06:48,050  INFO [ncms.loader.CmsResourceManager:1174] . Loader configuration : finished
24 Aug 2017 19:06:50,860 ERROR [apache.solr.core.CoreContainer: 832] Error creating core [spellcheck]: null
org.apache.solr.common.SolrException
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:820)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:658)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:820)
	at org.apache.solr.core.CoreContainer.access$000(CoreContainer.java:90)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:473)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:464)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor$1.run(ExecutorUtil.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.OverlappingFileLockException
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:114)
	at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41)
	at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45)
	at org.apache.lucene.index.IndexWriter.isLocked(IndexWriter.java:4487)
	at org.apache.solr.core.SolrCore.initIndex(SolrCore.java:522)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:761)
	... 10 more
24 Aug 2017 19:06:50,880 ERROR [apache.solr.core.CoreContainer: 832] Error creating core [Solr-Online]: null
org.apache.solr.common.SolrException
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:820)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:658)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:820)
	at org.apache.solr.core.CoreContainer.access$000(CoreContainer.java:90)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:473)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:464)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor$1.run(ExecutorUtil.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.OverlappingFileLockException
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:114)
	at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41)
	at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45)
	at org.apache.lucene.index.IndexWriter.isLocked(IndexWriter.java:4487)
	at org.apache.solr.core.SolrCore.initIndex(SolrCore.java:522)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:761)
	... 10 more
24 Aug 2017 19:06:50,880 ERROR [apache.solr.core.CoreContainer: 832] Error creating core [Solr-Offline]: null
org.apache.solr.common.SolrException
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:820)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:658)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:820)
	at org.apache.solr.core.CoreContainer.access$000(CoreContainer.java:90)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:473)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:464)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor$1.run(ExecutorUtil.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.OverlappingFileLockException
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:114)
	at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41)
	at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45)
	at org.apache.lucene.index.IndexWriter.isLocked(IndexWriter.java:4487)
	at org.apache.solr.core.SolrCore.initIndex(SolrCore.java:522)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:761)
	... 10 more
24 Aug 2017 19:06:50,882  INFO [pencms.search.CmsSearchManager:3081] . Search Solr          : Solr core container created using D:\apache-tomcat-8.5.20\webapps\opencms\WEB-INF\solr as Solr home and solr.xml as configuration file.
24 Aug 2017 19:06:52,512  WARN [pencms.search.CmsSearchManager:2587] . Search index         : Initialization of index "Solr Online" failed
org.apache.solr.common.SolrException: Error CREATEing SolrCore 'Solr-Online': Could not create a new core in D:\apache-tomcat-8.5.20\webapps\opencms\WEB-INF\solr\Solr Onlineas another core is already defined there
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:790)
	at org.opencms.search.CmsSearchManager.registerSolrIndex(CmsSearchManager.java:1797)
	at org.opencms.search.solr.CmsSolrIndex.initialize(CmsSolrIndex.java:428)
	at org.opencms.search.CmsSearchManager.initSearchIndexes(CmsSearchManager.java:2583)
	at org.opencms.search.CmsSearchManager.initializeIndexes(CmsSearchManager.java:1529)
	at org.opencms.search.CmsSearchManager.initialize(CmsSearchManager.java:1509)
	at org.opencms.main.OpenCmsCore.initConfiguration(OpenCmsCore.java:1431)
	at org.opencms.main.OpenCmsCore.initContext(OpenCmsCore.java:1534)
	at org.opencms.main.OpenCmsCore.upgradeRunlevel(OpenCmsCore.java:2090)
	at org.opencms.main.OpenCmsListener.contextInitialized(OpenCmsListener.java:85)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1144)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1878)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.common.SolrException: Could not create a new core in D:\apache-tomcat-8.5.20\webapps\opencms\WEB-INF\solr\Solr Onlineas another core is already defined there
	at org.apache.solr.core.CorePropertiesLocator.create(CorePropertiesLocator.java:65)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:760)
	... 22 more
24 Aug 2017 19:06:52,513  INFO [pencms.search.CmsSearchManager:2594] . Search index         : Successfully configured search index "Solr Online" for project "Online"
24 Aug 2017 19:06:52,921  WARN [pencms.search.CmsSearchManager:2587] . Search index         : Initialization of index "Solr Offline" failed
org.apache.solr.common.SolrException: Error CREATEing SolrCore 'Solr-Offline': Could not create a new core in D:\apache-tomcat-8.5.20\webapps\opencms\WEB-INF\solr\Solr Offlineas another core is already defined there
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:790)
	at org.opencms.search.CmsSearchManager.registerSolrIndex(CmsSearchManager.java:1797)
	at org.opencms.search.solr.CmsSolrIndex.initialize(CmsSolrIndex.java:428)
	at org.opencms.search.CmsSearchManager.initSearchIndexes(CmsSearchManager.java:2583)
	at org.opencms.search.CmsSearchManager.initializeIndexes(CmsSearchManager.java:1529)
	at org.opencms.search.CmsSearchManager.initialize(CmsSearchManager.java:1509)
	at org.opencms.main.OpenCmsCore.initConfiguration(OpenCmsCore.java:1431)
	at org.opencms.main.OpenCmsCore.initContext(OpenCmsCore.java:1534)
	at org.opencms.main.OpenCmsCore.upgradeRunlevel(OpenCmsCore.java:2090)
	at org.opencms.main.OpenCmsListener.contextInitialized(OpenCmsListener.java:85)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1144)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1878)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.common.SolrException: Could not create a new core in D:\apache-tomcat-8.5.20\webapps\opencms\WEB-INF\solr\Solr Offlineas another core is already defined there
	at org.apache.solr.core.CorePropertiesLocator.create(CorePropertiesLocator.java:65)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:760)
	... 22 more
24 Aug 2017 19:06:52,922  INFO [pencms.search.CmsSearchManager:2594] . Search index         : Successfully configured search index "Solr Offline" for project "Offline"
24 Aug 2017 19:06:53,019  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-flexible
24 Aug 2017 19:06:53,035  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-tabs
24 Aug 2017 19:06:53,036  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-sitemap
24 Aug 2017 19:06:53,036  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-navigation
24 Aug 2017 19:06:53,037  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-webform
24 Aug 2017 19:06:53,039  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-faq
24 Aug 2017 19:06:53,040  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : jsp-search
24 Aug 2017 19:06:53,041  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-imgursection
24 Aug 2017 19:06:53,041  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-job
24 Aug 2017 19:06:53,042  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : ugc_config
24 Aug 2017 19:06:53,042  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : subsitemap
24 Aug 2017 19:06:53,042  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : modelpage
24 Aug 2017 19:06:53,042  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : category
24 Aug 2017 19:06:53,042  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : htmlredirect
24 Aug 2017 19:06:53,042  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : containerpage
24 Aug 2017 19:06:53,043  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : groupcontainer
24 Aug 2017 19:06:53,043  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : elementview
24 Aug 2017 19:06:53,043  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : function
24 Aug 2017 19:06:53,043  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : seo_file
24 Aug 2017 19:06:53,043  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : containerpage_template
24 Aug 2017 19:06:53,043  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : content_folder
24 Aug 2017 19:06:53,043  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : sitemap_config
24 Aug 2017 19:06:53,043  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : module_config
24 Aug 2017 19:06:53,044  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : sitemap_master_config
24 Aug 2017 19:06:53,044  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : formatter_config
24 Aug 2017 19:06:53,044  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : inheritance_group
24 Aug 2017 19:06:53,044  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : inheritance_config
24 Aug 2017 19:06:53,044  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : xmlvfsbundle
24 Aug 2017 19:06:53,044  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : propertyvfsbundle
24 Aug 2017 19:06:53,044  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : modelgroup
24 Aug 2017 19:06:53,044  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : macro_formatter
24 Aug 2017 19:06:53,044  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : view_basic
24 Aug 2017 19:06:53,045  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : view_folders
24 Aug 2017 19:06:53,045  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : view_configs
24 Aug 2017 19:06:53,045  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : view_other
24 Aug 2017 19:06:53,045  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : bundledescriptor
24 Aug 2017 19:06:53,050  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-linksequence
24 Aug 2017 19:06:53,062  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-imagegallery
24 Aug 2017 19:06:53,064  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-slider
24 Aug 2017 19:06:53,071  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-event
24 Aug 2017 19:06:53,073  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-list
24 Aug 2017 19:06:53,080  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : uploadhtml
24 Aug 2017 19:06:53,081  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-map
24 Aug 2017 19:06:53,088  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-menu
24 Aug 2017 19:06:53,089  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-templaterow
24 Aug 2017 19:06:53,089  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-section
24 Aug 2017 19:06:53,097  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-shariff
24 Aug 2017 19:06:53,099  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-blog
24 Aug 2017 19:06:53,100  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-contact
24 Aug 2017 19:06:53,114  INFO [.workplace.CmsWorkplaceManager: 540] . Adding type setting  : a-sliderextended
24 Aug 2017 19:06:53,182  INFO [.workplace.CmsWorkplaceManager:2513] . Workplace view       : /system/workplace/views/admin/admin-fs.jsp
24 Aug 2017 19:06:53,196  INFO [.workplace.CmsWorkplaceManager:2513] . Workplace view       : /system/workplace/views/explorer/explorer_fs.jsp
24 Aug 2017 19:06:53,309  INFO [.workplace.CmsWorkplaceManager:1664] . Workplace config     : vfs access initialized
24 Aug 2017 19:06:53,419  INFO [uration.CmsDefaultUserSettings: 958] . Publish related resources mode is set to "true"
24 Aug 2017 19:06:53,420  INFO [uration.CmsDefaultUserSettings: 734] . Deletion of relation target resources is not allowed
24 Aug 2017 19:06:53,431  INFO [workplace.tools.CmsToolManager: 166] . Tool Manager config  : Tool Manager is being initialized
24 Aug 2017 19:06:56,642  WARN [workplace.tools.CmsToolManager: 707] . Tool Manager config  : inconsistent install path /searchindex/sourcesearch/fileslist for tool at /system/workplace/admin/searchindex/sourcesearch/fileslist.jsp.
24 Aug 2017 19:06:56,779  INFO [workplace.tools.CmsToolManager: 196] . Tool Manager config  : Successful configuration of the admin tool root
24 Aug 2017 19:06:56,944  INFO [workplace.tools.CmsToolManager: 196] . Tool Manager config  : Successful configuration of the explorer tool root
24 Aug 2017 19:06:57,090  INFO [de.configuration.CmsADEManager: 889] . Initializing the ADE configuration, this may take a while...
24 Aug 2017 19:06:57,101  INFO [de.configuration.CmsADEManager: 907] . Reading online configuration...
24 Aug 2017 19:06:57,114  INFO [guration.CmsConfigurationCache: 298] Read 6 config resources of type: sitemap_config from the online project.
24 Aug 2017 19:06:57,435  INFO [guration.CmsConfigurationCache: 336] Reading online module configurations.
24 Aug 2017 19:06:58,010  INFO [guration.CmsConfigurationCache: 341] Reading online element views.
24 Aug 2017 19:06:58,101  INFO [de.configuration.CmsADEManager: 909] . Reading offline configuration...
24 Aug 2017 19:06:58,114  INFO [guration.CmsConfigurationCache: 298] Read 6 config resources of type: sitemap_config from the offline project.
24 Aug 2017 19:06:58,474  INFO [guration.CmsConfigurationCache: 336] Reading offline module configurations.
24 Aug 2017 19:06:59,309  INFO [guration.CmsConfigurationCache: 341] Reading offline element views.
24 Aug 2017 19:06:59,377  INFO [de.configuration.CmsADEManager: 917] . Reading online inherited container configurations...
24 Aug 2017 19:06:59,394  INFO [de.configuration.CmsADEManager: 919] . Reading offline inherited container configurations...
24 Aug 2017 19:06:59,417  INFO [de.configuration.CmsADEManager: 923] . Reading online formatter configurations...
24 Aug 2017 19:07:01,369  INFO [de.configuration.CmsADEManager: 925] . Reading offline formatter configurations...
24 Aug 2017 19:07:02,927  INFO [de.configuration.CmsADEManager: 930] . Initializing online detail name cache...
24 Aug 2017 19:07:02,943  INFO [de.configuration.CmsADEManager: 932] . Initializing offline detail name cache...
24 Aug 2017 19:07:02,952  INFO [de.configuration.CmsADEManager: 945] . Done initializing the ADE configuration.
24 Aug 2017 19:07:03,331  INFO [  org.opencms.main.OpenCmsCore:2869] . Runlevel change      : Switching from 2 to 4
24 Aug 2017 19:07:03,364  INFO [  org.opencms.main.OpenCmsCore: 401] . Added RequestHandler : 404 (org.opencms.main.OpenCmsServlet)
24 Aug 2017 19:07:03,364  INFO [  org.opencms.main.OpenCmsCore:1681] . OpenCms is running!  : Total startup time was 00:00:22
24 Aug 2017 19:07:03,365  INFO [  org.opencms.main.OpenCmsCore:1685] .                      ...............................................................
24 Aug 2017 19:07:03,365  INFO [  org.opencms.main.OpenCmsCore:1686] .
24 Aug 2017 19:07:04,443  INFO [guration.CmsConfigurationCache: 298] Read 6 config resources of type: sitemap_config from the online project.
24 Aug 2017 19:07:05,146  INFO [guration.CmsConfigurationCache: 336] Reading online module configurations.
24 Aug 2017 19:07:05,834  INFO [guration.CmsConfigurationCache: 298] Read 6 config resources of type: sitemap_config from the offline project.
24 Aug 2017 19:07:06,236  INFO [guration.CmsConfigurationCache: 341] Reading online element views.
24 Aug 2017 19:07:06,672  INFO [guration.CmsConfigurationCache: 336] Reading offline module configurations.
24 Aug 2017 19:07:07,378  INFO [guration.CmsConfigurationCache: 341] Reading offline element views.
24 Aug 2017 19:07:39,830  INFO [rg.opencms.jsp.CmsJspLoginBean: 304] Successful login of user "Admin": Request from IP 0:0:0:0:0:0:0:1 using uri "/sites/default/login/index.html".
24 Aug 2017 19:08:00,791  INFO [rg.opencms.jsp.CmsJspLoginBean: 366] Logout of user "Admin": Request from IP 0:0:0:0:0:0:0:1 using uri "/sites/default/login/index.html".
24 Aug 2017 19:16:44,445  INFO [rg.opencms.jsp.CmsJspLoginBean: 304] Successful login of user "Admin": Request from IP 0:0:0:0:0:0:0:1 using uri "/sites/default/login/index.html".

```

**Comment by superc** [comment]
Because of the server.xml configuration in Tomcat, removed ```<Context>```  element in ```<Host>``` is ok.
