### ISSUE TITLE
Issue with replication of users

### ISSUE THREAD

**Issue by jeromediaz** [alkacon/opencms-core#527]
During replication of users we got lot of errors added to the log (when the master/contribution server fetch modifications from other servers)
on OpenCMS 9.5.3

05 Apr 2016 15:45:47,642 ERROR [lication.CmsReplicationManager:1431] Error while updating replication user with id 914f69ce-cc74-11e3-bc27-005056952927
org.opencms.file.CmsVfsException: Error deleting the user "xxxx".
	at org.opencms.file.CmsVfsException.createException(CmsVfsException.java:70)
	at org.opencms.db.CmsDbContext.throwException(CmsDbContext.java:334)
	at org.opencms.db.CmsDbContext.report(CmsDbContext.java:286)
	at org.opencms.db.CmsSecurityManager.deleteUser(CmsSecurityManager.java:6945)
	at org.opencms.db.CmsSecurityManager.deleteUser(CmsSecurityManager.java:1620)
	at org.opencms.file.CmsObject.deleteUser(CmsObject.java:965)
	at org.opencms.ocee.replication.CmsReplicationManager.synchronizeUsers(CmsReplicationManager.java:1336)
	at org.opencms.ocee.replication.CmsReplicationUserSyncJob.launch(CmsReplicationUserSyncJob.java:135)
	at org.opencms.scheduler.CmsScheduleManager.executeJob(CmsScheduleManager.java:568)
	at org.opencms.scheduler.CmsScheduleManager.execute(CmsScheduleManager.java:147)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:203)
	at org.opencms.scheduler.CmsSchedulerThread.run(CmsSchedulerThread.java:115)
Caused by: org.opencms.file.CmsVfsException: This operation is not allowed in the "Online" project.
	at org.opencms.db.CmsSecurityManager.checkProjectForDeletePrincipal(CmsSecurityManager.java:7227)
	at org.opencms.db.CmsSecurityManager.deleteUser(CmsSecurityManager.java:6938)
	... 8 more

**Comment by AntoinePineau** [comment]
Do you have any answer please ?

**Comment by gWestenberger** [comment]
OCEE issues don't really belong here.
