### ISSUE TITLE
Replication impossible when moving a folder from a site to shared folder

### ISSUE THREAD

**Issue by jeromediaz** [alkacon/opencms-core#531]
OpenCMS 9.5.2

After having moved a folder from a site to the shared folder, we are unable to publish (duplicate entry error). Seems like only files can be moved, not folders.

Publishing resources ...
Updating JSP loader cache...
.. JSP loader cache updated
Publishing folders ...
( 1 / 1 ) Publishing folder /shared/.content/faq/ ... o.k.
... finished publishing folders
Publishing files ...
( 1 / 1 ) Publishing file /shared/.content/faq/index.html ... o.k.
... finished publishing files
Statistics: published files: 1, published folders: 1, deleted folders: 0, duration: 00:00:01
... the resources have been published
Executing Accounts replication handler in incremental mode
Accounts replication handler in incremental mode finished!
Executing Vfs replication handler in incremental mode
Replicate resources filtered by /system/modules/:
Replicate resources filtered by /system/:
Replicate resources filtered by /shared/:
Replicating folders ...
( Replication1 ) Replicating /shared/.content/faq/ ... Error replicating VFS resource "/shared/.content/faq/" to replication server "Replication1"
Exception org.opencms.db.CmsDbSqlException: An SQL error occurred when executing the following query: com.mysql.jdbc.JDBC4PreparedStatement@3fb3878: INSERT INTO CMS_ONLINE_STRUCTURE (STRUCTURE_ID,RESOURCE_ID,RESOURCE_PATH,STRUCTURE_STATE,DATE_RELEASED,DATE_EXPIRED,PARENT_ID,STRUCTURE_VERSION) VALUES ('e241d867-44b6-11e4-aa9b-0050568879c5','e241d868-44b6-11e4-aa9b-0050568879c5','/shared/.content/faq',2,0,9223372036854775807,'4027e478-3553-11e2-a723-00c0f03d5b7c',0). 
at org.opencms.db.generic.CmsVfsDriver.createResource(CmsVfsDriver.java:793)
at org.opencms.ocee.replication.CmsReplicationVfsHandler$ReplicationContext.replicateFolder(CmsReplicationVfsHandler.java:807)
at org.opencms.ocee.replication.CmsReplicationVfsHandler$ReplicationContext.replicateVfsResources(CmsReplicationVfsHandler.java:266)
at org.opencms.ocee.replication.CmsReplicationVfsHandler.replicate(CmsReplicationVfsHandler.java:2015)
at org.opencms.ocee.replication.CmsReplicationManager.o000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000super(CmsReplicationManager.java:1864)
at org.opencms.ocee.replication.CmsReplicationManager.handleAfterPublishReplication(CmsReplicationManager.java:841)
at org.opencms.ocee.replication.CmsReplicationModuleAction.cmsEvent(CmsReplicationModuleAction.java:118)
at org.opencms.main.CmsEventManager.fireEventHandler(CmsEventManager.java:194)
at org.opencms.main.CmsEventManager.fireEvent(CmsEventManager.java:117)
at org.opencms.main.OpenCms.fireCmsEvent(OpenCms.java:154)
at org.opencms.publish.CmsPublishEngine.publishJobFinished(CmsPublishEngine.java:652)
at org.opencms.publish.CmsPublishThread.run(CmsPublishThread.java:180)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'e241d867-44b6-11e4-aa9b-0050568879c5' for key 'PRIMARY'
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:532)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
at com.mysql.jdbc.Util.getInstance(Util.java:386)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1040)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4074)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4006)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2468)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2629)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2719)
at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2450)
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2371)
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2355)
at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
at org.opencms.db.generic.CmsVfsDriver.createResource(CmsVfsDriver.java:711)
... 11 more
Replication stats: replicated files: 1, replicated folders: 0, deleted folders: 1, duration: 00:00:00 
Error during the replication process
Exception org.opencms.ocee.replication.CmsReplicationException: Error replicating VFS resource to replication server "Replication1"
at org.opencms.ocee.replication.CmsReplicationVfsHandler.replicate(CmsReplicationVfsHandler.java:2054)
at org.opencms.ocee.replication.CmsReplicationManager.o000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000super(CmsReplicationManager.java:1864)
at org.opencms.ocee.replication.CmsReplicationManager.handleAfterPublishReplication(CmsReplicationManager.java:841)
at org.opencms.ocee.replication.CmsReplicationModuleAction.cmsEvent(CmsReplicationModuleAction.java:118)
at org.opencms.main.CmsEventManager.fireEventHandler(CmsEventManager.java:194)
at org.opencms.main.CmsEventManager.fireEvent(CmsEventManager.java:117)
at org.opencms.main.OpenCms.fireCmsEvent(OpenCms.java:154)
at org.opencms.publish.CmsPublishEngine.publishJobFinished(CmsPublishEngine.java:652)
at org.opencms.publish.CmsPublishThread.run(CmsPublishThread.java:180)
Caused by: org.opencms.ocee.replication.CmsReplicationException: Error replicating VFS resource to replication server "Replication1"
at org.opencms.ocee.replication.CmsReplicationVfsHandler$ReplicationContext.replicateVfsResources(CmsReplicationVfsHandler.java:307)
at org.opencms.ocee.replication.CmsReplicationVfsHandler.replicate(CmsReplicationVfsHandler.java:2015)
... 8 more
Caused by: org.opencms.db.CmsDbSqlException: Error replicating VFS resource "/shared/.content/faq/" to replication server "Replication1"
at org.opencms.db.CmsDbSqlException.createException(CmsDbSqlException.java:109)
at org.opencms.db.CmsDbContext.throwException(CmsDbContext.java:334)
at org.opencms.db.CmsDbContext.report(CmsDbContext.java:286)
at org.opencms.ocee.replication.CmsReplicationVfsHandler$ReplicationContext.replicateFolder(CmsReplicationVfsHandler.java:1034)
at org.opencms.ocee.replication.CmsReplicationVfsHandler$ReplicationContext.replicateVfsResources(CmsReplicationVfsHandler.java:266)
... 9 more
Caused by: org.opencms.db.CmsDbSqlException: An SQL error occurred when executing the following query: com.mysql.jdbc.JDBC4PreparedStatement@3fb3878: INSERT INTO CMS_ONLINE_STRUCTURE (STRUCTURE_ID,RESOURCE_ID,RESOURCE_PATH,STRUCTURE_STATE,DATE_RELEASED,DATE_EXPIRED,PARENT_ID,STRUCTURE_VERSION) VALUES ('e241d867-44b6-11e4-aa9b-0050568879c5','e241d868-44b6-11e4-aa9b-0050568879c5','/shared/.content/faq',2,0,9223372036854775807,'4027e478-3553-11e2-a723-00c0f03d5b7c',0). 
at org.opencms.db.generic.CmsVfsDriver.createResource(CmsVfsDriver.java:793)
at org.opencms.ocee.replication.CmsReplicationVfsHandler$ReplicationContext.replicateFolder(CmsReplicationVfsHandler.java:807)
... 10 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'e241d867-44b6-11e4-aa9b-0050568879c5' for key 'PRIMARY'
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:532)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
at com.mysql.jdbc.Util.getInstance(Util.java:386)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1040)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4074)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4006)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2468)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2629)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2719)
at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2450)
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2371)
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2355)
at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
at org.opencms.db.generic.CmsVfsDriver.createResource(CmsVfsDriver.java:711)
... 11 more

**Comment by tHerrmann** [comment]
Hi, 
this seems to be an issue with the OCEE replication and not the OpenCms core. Please contact Alkacon support regarding the this problem.

Regards, Tobias
