### ISSUE TITLE
Exception - Index "Solr Offline" was not found.

### ISSUE THREAD

**Issue by Shaand** [alkacon/opencms-core#539]
I am getting the following exception in the log when click on "Select file" icon 

04 Oct 2017 07:07:19,901 ERROR [ org.opencms.gwt.CmsGwtService: 183] Index "Solr Offline" was not found.
org.opencms.main.CmsException: Index "Solr Offline" was not found.
        at org.opencms.search.galleries.CmsGallerySearch.setIndex(CmsGallerySearch.java:222)
        at org.opencms.ade.galleries.CmsGalleryService.findResourceInGallery(CmsGalleryService.java:2067)
        at org.opencms.ade.galleries.CmsGalleryService.getSearch(CmsGalleryService.java:885)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.opencms.gwt.CmsGwtService.service(CmsGwtService.java:194)
        at org.opencms.main.OpenCmsCore.invokeGwtService(OpenCmsCore.java:1719)
        at org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:158)
        at org.opencms.main.OpenCmsServlet.doPost(OpenCmsServlet.java:177)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.opencms.jsp.jsonpart.CmsJsonPartFilter.doFilter(CmsJsonPartFilter.java:281)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
04 Oct 2017 07:07:20,250 ERROR [ org.opencms.gwt.CmsLogService:  66] Client LOG (Host 172.30.20.66, Address 172.30.20.66, Ticket 1507097350176): (TypeError) : a is null
Unknown.Q3f(https://etb.piconsulting.co.uk/pi/handleStatic/v1448580202v/gwt/opencms/6F6EDC8A3140A0E1B488F80F18E9DD41.cache.html)
Unknown.xdf(https://etb.piconsulting.co.uk/pi/handleStatic/v1448580202v/gwt/opencms/6F6EDC8A3140A0E1B488F80F18E9DD41.cache.html)
Unknown.tff(https://etb.piconsulting.co.uk/pi/handleStatic/v1448580202v/gwt/opencms/6F6EDC8A3140A0E1B488F80F18E9DD41.cache.html)
Unknown.Itf(https://etb.piconsulting.co.uk/pi/handleStatic/v1448580202v/gwt/opencms/6F6EDC8A3140A0E1B488F80F18E9DD41.cache.html)
Unknown.Zof(https://etb.piconsulting.co.uk/pi/handleStatic/v1448580202v/gwt/opencms/6F6EDC8A3140A0E1B488F80F18E9DD41.cache.html)
Unknown.Fef(https://etb.piconsulting.co.uk/pi/handleStatic/v1448580202v/gwt/opencms/6F6EDC8A3140A0E1B488F80F18E9DD41.cache.html)
Unknown.Wdf(https://etb.piconsulting.co.uk/pi/handleStatic/v1448580202v/gwt/opencms/6F6EDC8A3140A0E1B488F80F18E9DD41.cache.html)
Unknown.Ydf(https://etb.piconsulting.co.uk/pi/handleStatic/v1448580202v/gwt/opencms/6F6EDC8A3140A0E1B488F80F18E9DD41.cache.html)
Unknown.ZZd(https://etb.piconsulting.co.uk/pi/handleStatic/v1448580202v/gwt/opencms/6F6EDC8A3140A0E1B488F80F18E9DD41.cache.html)
Unknown.jlc(https://etb.piconsulting.co.uk/pi/handleStatic/v1448580202v/gwt/opencms/6F6EDC8A3140A0E1B488F80F18E9DD41.cache.html)
Unknown.HR(https://etb.piconsulting.co.uk/pi/handleStatic/v1448580202v/gwt/opencms/6F6EDC8A3140A0E1B488F80F18E9DD41.cache.html)
Unknown.VR(https://etb.piconsulting.co.uk/pi/handleStatic/v1448580202v/gwt/opencms/6F6EDC8A3140A0E1B488F80F18E9DD41.cache.html)
Unknown.onreadystatechange<(https://etb.piconsulting.co.uk/pi/handleStatic/v1448580202v/gwt/opencms/6F6EDC8A3140A0E1B488F80F18E9DD41.cache.html)
Unknown.BD(https://etb.piconsulting.co.uk/pi/handleStatic/v1448580202v/gwt/opencms/6F6EDC8A3140A0E1B488F80F18E9DD41.cache.html)
Unknown.ED(https://etb.piconsulting.co.uk/pi/handleStatic/v1448580202v/gwt/opencms/6F6EDC8A3140A0E1B488F80F18E9DD41.cache.html)
Unknown.DD/<(https://etb.piconsulting.co.uk/pi/handleStatic/v1448580202v/gwt/opencms/6F6EDC8A3140A0E1B488F80F18E9DD41.cache.html)
Unknown.anonymous(Unknown)

**Comment by Shaand** [comment]
![2017-10-04_122704](https://user-images.githubusercontent.com/7913072/31163287-677fc936-a8ff-11e7-9237-47e57eba8d4e.jpg)

**Comment by Shaand** [comment]
FYI, we upgraded 9.0.1 to 10.5.2 

and on 9.0.1 we didn't use solr indexing.

**Comment by kartobi** [comment]
You'll need Solr Offline as it is use for gallery wizard in cms editor. It replaces "Gallery Index", which was used before.

**Comment by Shaand** [comment]
Hi, Please could you let me know the steps to enable Solr offline

**Comment by Shaand** [comment]
If possible, please provide the complete xml

**Comment by kartobi** [comment]
See opencms-search.xml in your opencms.war or here: https://github.com/alkacon/opencms-core/blob/branch_10_5_x/webapp/WEB-INF/config/opencms-search.xml

**Comment by tHerrmann** [comment]
This solved by adding the Solr offline index to the search configuration.
