### ISSUE TITLE
about:lkacon OAMP Comments Module Version 2.0.0 error

### ISSUE THREAD

**Issue by g4495792** [alkacon/opencms-core#549]
不能解析XML内容定义模式“opencms://system/modules/com.alkacon.opencms.v8.comments/schemas/comment.xsd”。

org.opencms.main.CmsRuntimeException: 不能解析XML内容定义模式“opencms://system/modules/com.alkacon.opencms.v8.comments/schemas/comment.xsd”。

	at org.opencms.xml.content.CmsXmlContent.getContentDefinition(CmsXmlContent.java:937)

	at org.opencms.xml.content.CmsXmlContent.<init>(CmsXmlContent.java:139)

	at org.opencms.xml.content.CmsXmlContentFactory.unmarshal(CmsXmlContentFactory.java:321)

	at org.opencms.xml.content.CmsXmlContentFactory.unmarshal(CmsXmlContentFactory.java:163)

	at org.opencms.xml.content.CmsXmlContentFactory.unmarshal(CmsXmlContentFactory.java:237)

	at org.opencms.xml.content.CmsXmlContentFactory.unmarshal(CmsXmlContentFactory.java:184)

	at org.opencms.workplace.editors.CmsWorkplaceEditorManager.checkAcaciaEditorAvailable(CmsWorkplaceEditorManager.java:162)

	at org.opencms.ui.editors.CmsAcaciaEditor.matchesResource(CmsAcaciaEditor.java:70)

	at org.opencms.ui.apps.CmsWorkplaceAppManager.getEditorForResource(CmsWorkplaceAppManager.java:332)

	at org.opencms.ui.apps.CmsEditor.onStateChange(CmsEditor.java:208)

	at org.opencms.ui.apps.CmsAppView.enter(CmsAppView.java:229)

	at org.opencms.ui.apps.CmsAppView.enter(CmsAppView.java:242)

	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:621)

	at org.opencms.ui.apps.CmsAppNavigator.navigateTo(CmsAppNavigator.java:65)

	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:580)

	at org.opencms.ui.apps.CmsAppWorkplaceUi.showApp(CmsAppWorkplaceUi.java:434)

	at org.opencms.ui.actions.CmsEditDialogAction.executeAction(CmsEditDialogAction.java:77)

	at org.opencms.ui.components.CmsFileTable.handleFileItemClick(CmsFileTable.java:855)

	at org.opencms.ui.components.CmsFileTable$2.itemClick(CmsFileTable.java:396)

	at sun.reflect.GeneratedMethodAccessor190.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)

	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)

	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)

	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1015)

	at com.vaadin.ui.Table.handleClickEvent(Table.java:3162)

	at com.vaadin.ui.Table.changeVariables(Table.java:2952)

	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:627)

	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:461)

	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:411)

	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273)

	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)

	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)

	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1422)

	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:379)

	at org.opencms.main.CmsUIServlet.service(CmsUIServlet.java:302)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

	at org.opencms.main.OpenCmsUrlServletFilter.doFilter(OpenCmsUrlServletFilter.java:132)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)

	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)

	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)

	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)

	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)

	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)

	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)

	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)

	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)

	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)

	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

	at java.lang.Thread.run(Thread.java:745)

Caused by: org.opencms.xml.CmsXmlException: 在内容定义“opencms://system/modules/com.alkacon.opencms.v8.comments/schemas/optionalformcaptcha.xsd”自定义的组件类“com.alkacon.opencms.v8.formgenerator.CmsSelectWidgetXmlcontentType”对元素“Preset”无效。

	at org.opencms.xml.content.CmsDefaultXmlContentHandler.addWidget(CmsDefaultXmlContentHandler.java:1907)

	at org.opencms.xml.content.CmsDefaultXmlContentHandler.initLayouts(CmsDefaultXmlContentHandler.java:2239)

	at org.opencms.xml.content.CmsDefaultXmlContentHandler.initialize(CmsDefaultXmlContentHandler.java:1181)

	at org.opencms.xml.CmsXmlContentDefinition.unmarshalInternal(CmsXmlContentDefinition.java:1016)

	at org.opencms.xml.CmsXmlContentDefinition.unmarshal(CmsXmlContentDefinition.java:437)

	at org.opencms.xml.CmsXmlContentDefinition.unmarshalInternal(CmsXmlContentDefinition.java:917)

	at org.opencms.xml.CmsXmlContentDefinition.unmarshal(CmsXmlContentDefinition.java:465)

	at org.opencms.xml.content.CmsXmlContent.getContentDefinition(CmsXmlContent.java:931)

	... 60 more

Caused by: java.lang.ClassNotFoundException: com.alkacon.opencms.v8.formgenerator.CmsSelectWidgetXmlcontentType

	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1892)

	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)

	at java.lang.Class.forName0(Native Method)

	at java.lang.Class.forName(Class.java:264)

	at org.opencms.xml.content.CmsDefaultXmlContentHandler.addWidget(CmsDefaultXmlContentHandler.java:1899)

	... 67 more

**Comment by tHerrmann** [comment]
Please use the OAMP repository to report this issue there. This issue list is used for the OpenCms core only.
