### ISSUE TITLE
NPE when reading config: not enough diagnostics

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#569]
In one of my test environments, OpenCms (only) logs the following message, so I have to debug to know what is going on:

```
25 Jan 2018 11:12:07,649 ERROR [uration.CmsConfigurationReader: 716]
java.lang.NullPointerException
        at org.opencms.relations.CmsRelationType.valueOfInternal(CmsRelationType.java:492)
        at org.opencms.relations.CmsRelationType.valueOfXml(CmsRelationType.java:462)
        at org.opencms.relations.CmsLink.<init>(CmsLink.java:146)
        at org.opencms.xml.types.CmsXmlVfsFileValue.getLink(CmsXmlVfsFileValue.java:172)
        at org.opencms.xml.content.CmsDefaultXmlContentHandler.validateLink(CmsDefaultXmlContentHandler.java:3103)
        at org.opencms.xml.content.CmsDefaultXmlContentHandler.invalidateBrokenLinks(CmsDefaultXmlContentHandler.java:1268)
        at org.opencms.xml.content.CmsXmlContent.initDocument(CmsXmlContent.java:959)
        at org.opencms.xml.content.CmsXmlContent.<init>(CmsXmlContent.java:141)
        at org.opencms.xml.content.CmsXmlContentFactory.unmarshal(CmsXmlContentFactory.java:321)
        at org.opencms.xml.content.CmsXmlContentFactory.unmarshal(CmsXmlContentFactory.java:163)
        at org.opencms.xml.content.CmsXmlContentFactory.unmarshal(CmsXmlContentFactory.java:237)
        at org.opencms.xml.content.CmsXmlContentFactory.unmarshal(CmsXmlContentFactory.java:184)
        at org.opencms.ade.configuration.CmsConfigurationReader.parseSitemapConfiguration(CmsConfigurationReader.java:687)
        at org.opencms.ade.configuration.CmsConfigurationReader.readModuleConfigurations(CmsConfigurationReader.java:707)
        at org.opencms.ade.configuration.CmsConfigurationCache.loadModuleConfiguration(CmsConfigurationCache.java:510)
        at org.opencms.ade.configuration.CmsConfigurationCache.readCompleteConfiguration(CmsConfigurationCache.java:340)
        at org.opencms.ade.configuration.CmsConfigurationCache.performUpdate(CmsConfigurationCache.java:539)
        at org.opencms.ade.configuration.CmsConfigurationCache$2.run(CmsConfigurationCache.java:256)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by gallardo** [comment]
This seems related. No diagnostics either:

```
25 Jan 2018 11:12:53,450  INFO [  org.opencms.main.OpenCmsCore:1968] . OpenCms stopped!     : Total uptime was 00:00:08
25 Jan 2018 11:12:53,450  INFO [  org.opencms.main.OpenCmsCore:1969] .                      ...............................................................
25 Jan 2018 11:12:53,450  INFO [  org.opencms.main.OpenCmsCore:1970] .
25 Jan 2018 11:12:53,450  INFO [  org.opencms.main.OpenCmsCore:1971] .
25 Jan 2018 11:12:53,451  INFO [.opencms.i18n.CmsLocaleManager: 432] . i18n configuration   : the JVM default locale is "en"
25 Jan 2018 11:12:53,451 ERROR [uration.CmsADEConfigCacheState: 117]
java.lang.NullPointerException
        at org.opencms.main.OpenCmsCore.initCmsObject(OpenCmsCore.java:2488)
        at org.opencms.main.OpenCmsCore.initCmsObject(OpenCmsCore.java:943)
        at org.opencms.main.OpenCms.initCmsObject(OpenCms.java:629)
        at org.opencms.ade.configuration.CmsADEConfigData.getFolderTypes(CmsADEConfigData.java:948)
        at org.opencms.ade.configuration.CmsADEConfigCacheState.computeFolderTypes(CmsADEConfigCacheState.java:148)
        at org.opencms.ade.configuration.CmsADEConfigCacheState.<init>(CmsADEConfigCacheState.java:114)
        at org.opencms.ade.configuration.CmsConfigurationCache.readCompleteConfiguration(CmsConfigurationCache.java:346)
        at org.opencms.ade.configuration.CmsConfigurationCache.performUpdate(CmsConfigurationCache.java:539)
        at org.opencms.ade.configuration.CmsConfigurationCache$2.run(CmsConfigurationCache.java:256)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
25 Jan 2018 11:12:54,756  INFO [       org.opencms.main.CmsLog: 117] . Log4j config file    : /var/lib/tomcat8/webapps-install/ROOT/WEB-INF/classes/log4j.properties

```

**Comment by tHerrmann** [comment]
These errors are very unusual. Are you sure, there are no previous exceptions during the OpenCms initialization?
Both errors should only occur in case the OpenCms is not fully initialized.

**Comment by tHerrmann** [comment]
Is there any way to reproduce these issues?

**Comment by dSeidel** [comment]
No discussion for years, closing the issue.
