### ISSUE TITLE
Compatibility of OCEE 5.5.3 and OpenCMS 10.5.3 in MS SQL Server

### ISSUE THREAD

**Issue by josealbertopf** [alkacon/opencms-core#580]
HI,

we have detected a problem in the installation of "**Alkacon OCEE 5.5.3**" with "**OpenCMS 10.5.3**" running in "**MS SQL Server 2008**" (also in "MS SQL Server 2014"). When the "**OCEE Accelerator**" module is installed on a clean instance of OpenCMS, the following error occurs and the application is not deployed correctly:

```
23 feb 2018 09:46:45,853 FATAL [.opencms.db.CmsSecurityManager:3417] Critical error while loading driver manager.
java.lang.NullPointerException
    at org.opencms.ocee.cache.CmsUserCache.readUser(CmsUserCache.java:850)
    at org.opencms.db.CmsDriverManager.readUser(CmsDriverManager.java:8133)
    at org.opencms.publish.CmsPublishEngine.setDriverManager(CmsPublishEngine.java:309)
    at org.opencms.db.CmsDriverManager.init(CmsDriverManager.java:5167)
installation    at org.opencms.db.CmsSecurityManager.init(CmsSecurityManager.java:3410)
    at org.opencms.db.CmsSecurityManager.newInstance(CmsSecurityManager.java:166)
    at org.opencms.main.OpenCmsCore.initConfiguration(OpenCmsCore.java:1358)
    at org.opencms.main.OpenCmsCore.initContext(OpenCmsCore.java:1534)
    at org.opencms.main.OpenCmsCore.upgradeRunlevel(OpenCmsCore.java:2090)
    at org.opencms.main.OpenCmsListener.contextInitialized(OpenCmsListener.java:85)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5027)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5525)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
    at org.apache.catalina.core.ContainerBase.access$000(ContainerBase.java:133)
    at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:156)
    at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:145)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1247)
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1897)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
    at java.lang.Thread.run(Thread.java:748)
23 feb 2018 09:46:45,856 ERROR [  org.opencms.main.OpenCmsCore: 370] Critical error while loading driver manager.
org.opencms.main.CmsException: Critical error while loading driver manager.
    at org.opencms.main.OpenCmsCore.setErrorCondition(OpenCmsCore.java:370)
    at org.opencms.main.CmsInitException.setErrorCondition(CmsInitException.java:113)
    at org.opencms.main.CmsInitException.<init>(CmsInitException.java:84)
    at org.opencms.db.CmsSecurityManager.init(CmsSecurityManager.java:3419)
    at org.opencms.db.CmsSecurityManager.newInstance(CmsSecurityManager.java:166)
    at org.opencms.main.OpenCmsCore.initConfiguration(OpenCmsCore.java:1358)
    at org.opencms.main.OpenCmsCore.initContext(OpenCmsCore.java:1534)
    at org.opencms.main.OpenCmsCore.upgradeRunlevel(OpenCmsCore.java:2090)
    at org.opencms.main.OpenCmsListener.contextInitialized(OpenCmsListener.java:85)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5027)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5525)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
    at org.apache.catalina.core.ContainerBase.access$000(ContainerBase.java:133)
    at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:156)
    at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:145)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1247)
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1897)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
    at java.lang.Thread.run(Thread.java:748)
23 feb 2018 09:46:45,857 ERROR [g.opencms.main.OpenCmsListener:  89] Critical error while loading driver manager.
org.opencms.main.CmsInitException: Critical error while loading driver manager.
    at org.opencms.db.CmsSecurityManager.init(CmsSecurityManager.java:3419)
    at org.opencms.db.CmsSecurityManager.newInstance(CmsSecurityManager.java:166)
    at org.opencms.main.OpenCmsCore.initConfiguration(OpenCmsCore.java:1358)
    at org.opencms.main.OpenCmsCore.initContext(OpenCmsCore.java:1534)
    at org.opencms.main.OpenCmsCore.upgradeRunlevel(OpenCmsCore.java:2090)
    at org.opencms.main.OpenCmsListener.contextInitialized(OpenCmsListener.java:85)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5027)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5525)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
    at org.apache.catalina.core.ContainerBase.access$000(ContainerBase.java:133)
    at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:156)
    at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:145)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1247)
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1897)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
    at org.opencms.ocee.cache.CmsUserCache.readUser(CmsUserCache.java:850)
    at org.opencms.db.CmsDriverManager.readUser(CmsDriverManager.java:8133)
    at org.opencms.publish.CmsPublishEngine.setDriverManager(CmsPublishEngine.java:309)
    at org.opencms.db.CmsDriverManager.init(CmsDriverManager.java:5167)
    at org.opencms.db.CmsSecurityManager.init(CmsSecurityManager.java:3410)
    ... 22 more
```

Reviewing the compatibility notes of OCEE (*) we see that the current versions of MS SQL Server are supported so we understand that it could bea bug. If so, we would appreciate your correction as soon as possible.

Regards!

(*) http://www.alkacon.com/en/products/ocee/ocee_compatibility.html

``

**Comment by josealbertopf** [comment]
As complementary information: our current infrastructure consists of several instances of OpenCMS 9.5.3 together with OCEE 4.5.4 in MS SQL Server 2008 and it works perfectly. We also have done several tests with MS SQL Server 2014 and the result has been satisfactory.

**Comment by tHerrmann** [comment]
The Alkacon OCEE modules are compatible with MSSQL-Server. If you have any further questions please contact Alkacon at http://www.alkacon.com/en/company/contact/form.html.
