### ISSUE TITLE
CmsDbSqlException while restart of Tomcat

### ISSUE THREAD

**Issue by omkarswami** [alkacon/opencms-core#583]
I have written a filter for adding browser caching headers to images which are served from OpenCMS.
`import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
 
import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.http.HttpServletResponse;
import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
public class HeaderFilter implements Filter {
    
    private static final Logger logger = LogManager.getLogger(HeaderFilter.class);
    private Integer years = 1;
 
    @Override
    public void destroy() {
    }
 
    @Override
    public void doFilter(ServletRequest request, ServletResponse response,
            FilterChain chain) throws IOException, ServletException {
        logger.debug("INSIDE doFilter--------->");
        if (years > -1) {
        logger.debug("INSIDE if--------->");
            Calendar c = Calendar.getInstance();
            c.setTime(new Date());
            c.add(Calendar.YEAR, years);
            // HTTP header date format: Thu, 01 Dec 1994 16:00:00 GMT
        logger.debug("Previous header--------->"+((HttpServletResponse) response).getHeader("Expires"));
            String o = new SimpleDateFormat("EEE, d MMM yyyy HH:mm:ss zzz")
                    .format(c.getTime());
            ((HttpServletResponse) response).setHeader("Expires", o);
            ((HttpServletResponse) response).setHeader("Cache-Control", "max-age=31536000, public, must-revalidate");
        logger.debug("Modified header--------->"+((HttpServletResponse) response).getHeader("Expires"));
        }
 
        chain.doFilter(request, response);
    }
 
    @Override
    public void init(FilterConfig filterConfig) throws ServletException {  
        logger.debug("HEADER FILTER INIT--------->");
    }
}
`
and added filter and filter mapping entry in web.xml of opencms at path /WEB-INF/web.xml

After placing jar containing HeaderFilter in /WEB-INF/lib and adding above entries in web.xml. I restarted  the Tomcat on which OpenCMS is installed. I got following error in opencms.log while restart
`org.opencms.db.CmsDbSqlException: An SQL error occurred when executing the following query: . 
	at org.opencms.db.generic.CmsUserDriver.existsGroup(CmsUserDriver.java:764)
	at org.opencms.db.generic.CmsUserDriver.internalCreateDefaultGroups(CmsUserDriver.java:2196)
	at org.opencms.db.generic.CmsUserDriver.fillDefaults(CmsUserDriver.java:819)
	at org.opencms.db.CmsDriverManager.init(CmsDriverManager.java:5073)
	at org.opencms.db.CmsSecurityManager.init(CmsSecurityManager.java:3342)
	at org.opencms.db.CmsSecurityManager.newInstance(CmsSecurityManager.java:165)
	at org.opencms.main.OpenCmsCore.initConfiguration(OpenCmsCore.java:1292)
	at org.opencms.main.OpenCmsCore.initContext(OpenCmsCore.java:1461)
	at org.opencms.main.OpenCmsCore.upgradeRunlevel(OpenCmsCore.java:2013)
	at org.opencms.main.OpenCmsListener.contextInitialized(OpenCmsListener.java:85)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5528)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardContext.reload(StandardContext.java:4033)
	at org.apache.catalina.startup.HostConfig.reload(HostConfig.java:1524)
	at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1497)
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1695)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:333)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1374)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1546)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1556)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1524)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://CDTMYSQL1:5123/sotcopencmsdb4uat?characterEncoding=UTF-8
	at java.sql.DriverManager.getConnection(DriverManager.java:596)
	at java.sql.DriverManager.getConnection(DriverManager.java:187)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:78)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1158)
	at org.apache.commons.dbcp.PoolingDriver.connect(PoolingDriver.java:180)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:233)
	at org.opencms.db.CmsSqlManager.getConnectionByUrl(CmsSqlManager.java:96)
	at org.opencms.db.generic.CmsSqlManager.getConnection(CmsSqlManager.java:224)
	at org.opencms.db.generic.CmsUserDriver.existsGroup(CmsUserDriver.java:746)
	... 24 more
27 Feb 2018 08:44:23,788 ERROR [  org.opencms.main.OpenCmsCore: 359] Critical error during OpenCms initialization: Unable to initialize the user driver. 
org.opencms.main.CmsException: Critical error during OpenCms initialization: Unable to initialize the user driver. 
	at org.opencms.main.OpenCmsCore.setErrorCondition(OpenCmsCore.java:359)
	at org.opencms.main.CmsInitException.setErrorCondition(CmsInitException.java:113)
	at org.opencms.main.CmsInitException.<init>(CmsInitException.java:84)
	at org.opencms.db.generic.CmsUserDriver.internalCreateDefaultGroups(CmsUserDriver.java:2207)
	at org.opencms.db.generic.CmsUserDriver.fillDefaults(CmsUserDriver.java:819)
	at org.opencms.db.CmsDriverManager.init(CmsDriverManager.java:5073)
	at org.opencms.db.CmsSecurityManager.init(CmsSecurityManager.java:3342)
	at org.opencms.db.CmsSecurityManager.newInstance(CmsSecurityManager.java:165)
	at org.opencms.main.OpenCmsCore.initConfiguration(OpenCmsCore.java:1292)
	at org.opencms.main.OpenCmsCore.initContext(OpenCmsCore.java:1461)
	at org.opencms.main.OpenCmsCore.upgradeRunlevel(OpenCmsCore.java:2013)
	at org.opencms.main.OpenCmsListener.contextInitialized(OpenCmsListener.java:85)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5528)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardContext.reload(StandardContext.java:4033)
	at org.apache.catalina.startup.HostConfig.reload(HostConfig.java:1524)
	at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1497)
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1695)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:333)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1374)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1546)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1556)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1524)
	at java.lang.Thread.run(Thread.java:745)
27 Feb 2018 08:44:23,789 FATAL [.opencms.db.CmsSecurityManager:3349] Critical error while loading driver manager.
org.opencms.main.CmsInitException: Critical error during OpenCms initialization: Unable to initialize the user driver. 
	at org.opencms.db.generic.CmsUserDriver.internalCreateDefaultGroups(CmsUserDriver.java:2207)
	at org.opencms.db.generic.CmsUserDriver.fillDefaults(CmsUserDriver.java:819)
	at org.opencms.db.CmsDriverManager.init(CmsDriverManager.java:5073)
	at org.opencms.db.CmsSecurityManager.init(CmsSecurityManager.java:3342)
	at org.opencms.db.CmsSecurityManager.newInstance(CmsSecurityManager.java:165)
	at org.opencms.main.OpenCmsCore.initConfiguration(OpenCmsCore.java:1292)
	at org.opencms.main.OpenCmsCore.initContext(OpenCmsCore.java:1461)
	at org.opencms.main.OpenCmsCore.upgradeRunlevel(OpenCmsCore.java:2013)
	at org.opencms.main.OpenCmsListener.contextInitialized(OpenCmsListener.java:85)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5528)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardContext.reload(StandardContext.java:4033)
	at org.apache.catalina.startup.HostConfig.reload(HostConfig.java:1524)
	at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1497)
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1695)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:333)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1374)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1546)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1556)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1524)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.opencms.db.CmsDbSqlException: An SQL error occurred when executing the following query: . 
	at org.opencms.db.generic.CmsUserDriver.existsGroup(CmsUserDriver.java:764)
	at org.opencms.db.generic.CmsUserDriver.internalCreateDefaultGroups(CmsUserDriver.java:2196)
	... 23 more
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://CDTMYSQL1:5123/sotcopencmsdb4uat?characterEncoding=UTF-8
	at java.sql.DriverManager.getConnection(DriverManager.java:596)
	at java.sql.DriverManager.getConnection(DriverManager.java:187)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:78)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1158)
	at org.apache.commons.dbcp.PoolingDriver.connect(PoolingDriver.java:180)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:233)
	at org.opencms.db.CmsSqlManager.getConnectionByUrl(CmsSqlManager.java:96)
	at org.opencms.db.generic.CmsSqlManager.getConnection(CmsSqlManager.java:224)
	at org.opencms.db.generic.CmsUserDriver.existsGroup(CmsUserDriver.java:746)
	... 24 more
27 Feb 2018 08:44:23,789 ERROR [g.opencms.main.OpenCmsListener:  89] Critical error while loading driver manager.
org.opencms.main.CmsInitException: Critical error while loading driver manager.
	at org.opencms.db.CmsSecurityManager.init(CmsSecurityManager.java:3351)
	at org.opencms.db.CmsSecurityManager.newInstance(CmsSecurityManager.java:165)
	at org.opencms.main.OpenCmsCore.initConfiguration(OpenCmsCore.java:1292)
	at org.opencms.main.OpenCmsCore.initContext(OpenCmsCore.java:1461)
	at org.opencms.main.OpenCmsCore.upgradeRunlevel(OpenCmsCore.java:2013)
	at org.opencms.main.OpenCmsListener.contextInitialized(OpenCmsListener.java:85)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5528)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardContext.reload(StandardContext.java:4033)
	at org.apache.catalina.startup.HostConfig.reload(HostConfig.java:1524)
	at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1497)
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1695)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:333)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1374)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1546)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1556)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1524)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.opencms.main.CmsInitException: Critical error during OpenCms initialization: Unable to initialize the user driver. 
	at org.opencms.db.generic.CmsUserDriver.internalCreateDefaultGroups(CmsUserDriver.java:2207)
	at org.opencms.db.generic.CmsUserDriver.fillDefaults(CmsUserDriver.java:819)
	at org.opencms.db.CmsDriverManager.init(CmsDriverManager.java:5073)
	at org.opencms.db.CmsSecurityManager.init(CmsSecurityManager.java:3342)
	... 20 more
Caused by: org.opencms.db.CmsDbSqlException: An SQL error occurred when executing the following query: . 
	at org.opencms.db.generic.CmsUserDriver.existsGroup(CmsUserDriver.java:764)
	at org.opencms.db.generic.CmsUserDriver.internalCreateDefaultGroups(CmsUserDriver.java:2196)
	... 23 more
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://CDTMYSQL1:5123/sotcopencmsdb4uat?characterEncoding=UTF-8
	at java.sql.DriverManager.getConnection(DriverManager.java:596)
	at java.sql.DriverManager.getConnection(DriverManager.java:187)
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:78)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1158)
	at org.apache.commons.dbcp.PoolingDriver.connect(PoolingDriver.java:180)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:233)
	at org.opencms.db.CmsSqlManager.getConnectionByUrl(CmsSqlManager.java:96)
	at org.opencms.db.generic.CmsSqlManager.getConnection(CmsSqlManager.java:224)
	at org.opencms.db.generic.CmsUserDriver.existsGroup(CmsUserDriver.java:746)
	... 24 more
`
I am using OpenCMS version 9.5.1.

After I reverted my changes and restarted the server **without placing any db driver jar in lib folder** and it restarted without any error.
Why above exception occured?

**Comment by tHerrmann** [comment]
You should already have the mysql driver JAR in the OpenCms lib folder. Look for 'mysql-connector-java-5.1.45-bin.jar'. That is the version supplied by OpenCms.
I wonder, if adding the filter class and adjusting the web.xml where the only changes you did. We have been using filters without any issues.
