### ISSUE TITLE
Failed test:  testIndexGeneration

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#585]
Commit 9b55c1fff973060f51012edac6559ad6c8568a82 breaks the test `org.opencms.search.solr.TestSolrSearch#testIndexGeneration` in our ci environment. (The tests succeed however in development environments.) The probably most relevant difference between environments is that our ci builds opencms-core in a nfs mount.

`testIndexGeneration` fails while trying to remove the index "Test new index" with following error:

>  ERROR [ache.solr.common.SolrException: 159] Error removing directory:java.io.IOException: Unable to delete directory /workspace/opencms-core/test/data/WEB-INF/index/Test new index/spellchecker.

The next test (`org.opencms.search.solr.TestSolrSearch#testIssueWithSpecialFoldernames`) hangs forever after reporting a

> org.apache.solr.common.SolrException: No such core: Test-new-index

Unfortunately, solr's `CachingDirectoryFactory` is catching and silencing an Exception, so it doesn't look trivial to detect this condition and recover from it (see https://github.com/apache/lucene-solr/blob/releases/lucene-solr/7.2.1/solr/core/src/java/org/apache/solr/core/CachingDirectoryFactory.java#L208) :

```java
      for (CacheValue val : removeEntries) {
        log.debug("Removing directory after core close: " + val.path);
        try {
          removeDirectory(val);
        } catch (Exception e) {
          SolrException.log(log, "Error removing directory", e);
        }
      }
```

Following is the test log. I have abbreviated the paths and skipped some uninteresting  fragments:
```
     +------------------------------------------------------------------------------
     | Running OpenCms test case:
     | org.opencms.search.solr.TestSolrSearch#testIndexGeneration
     +------------------------------------------------------------------------------

    16 Mar 2018 18:56:00,858  INFO [pencms.search.CmsSearchManager:1821] . Search Solr          : Embedded Solr server created for index Test new index (Test-new-index). 
    16 Mar 2018 18:56:00,858  INFO [pencms.search.CmsSearchManager: 934] . Search indices       : Adding "Test new index" for project Offline
    16 Mar 2018 18:56:00,859  INFO [search.solr.CmsSolrIndexWriter:  95] Creating new writer for search index "Test new index" (/workspace/opencms-core/test/data/WEB-INF/index/Test new index).
    16 Mar 2018 18:56:00,859  INFO [search.solr.CmsSolrIndexWriter: 139] Deleting all documents in search index "Test new index" (/workspace/opencms-core/test/data/WEB-INF/index/Test new index).
    ------ Rebuilding search index "Test new index"
    ( 1 ) Indexing file /sites/default/TESTuppercase/master.pdf ... skipped
    16 Mar 2018 18:56:00,873  INFO [g.opencms.search.CmsVfsIndexer: 306] Deleting resource /sites/default/TESTuppercase/master.pdf from index
    16 Mar 2018 18:56:00,873  INFO [search.solr.CmsSolrIndexWriter: 158] Deleting document "/sites/default/TESTuppercase/master.pdf" in search index "Test new index" (/workspace/opencms-core/test/data/WEB-INF/index/Test new index).
    ( 2 ) Indexing file /sites/default/folder1/image1.gif ... skipped
    16 Mar 2018 18:56:00,880  INFO [g.opencms.search.CmsVfsIndexer: 306] Deleting resource /sites/default/folder1/image1.gif from index
    16 Mar 2018 18:56:00,880  INFO [search.solr.CmsSolrIndexWriter: 158] Deleting document "/sites/default/folder1/image1.gif" in search index "Test new index" (/workspace/opencms-core/test/data/WEB-INF/index/Test new index).
    ( 3 ) Indexing file /sites/default/folder1/image2.gif ... skipped
    16 Mar 2018 18:56:00,881  INFO [g.opencms.search.CmsVfsIndexer: 306] Deleting resource /sites/default/folder1/image2.gif from index
    16 Mar 2018 18:56:00,881  INFO [search.solr.CmsSolrIndexWriter: 158] Deleting document "/sites/default/folder1/image2.gif" in search index "Test new index" (/workspace/opencms-core/test/data/WEB-INF/index/Test new index).
    [...]

    ( 48 ) Indexing file /sites/default/types/xml.xml ... skipped
    16 Mar 2018 18:56:01,046  INFO [g.opencms.search.CmsVfsIndexer: 306] Deleting resource /sites/default/types/xml.xml from index
    16 Mar 2018 18:56:01,046  INFO [search.solr.CmsSolrIndexWriter: 158] Deleting document "/sites/default/types/xml.xml" in search index "Test new index" (/workspace/opencms-core/test/data/WEB-INF/index/Test new index).
    ( 49 ) Indexing file /sites/default/xmlcontent/article.xsd ... skipped
    16 Mar 2018 18:56:01,047  INFO [g.opencms.search.CmsVfsIndexer: 306] Deleting resource /sites/default/xmlcontent/article.xsd from index
    16 Mar 2018 18:56:01,048  INFO [search.solr.CmsSolrIndexWriter: 158] Deleting document "/sites/default/xmlcontent/article.xsd" in search index "Test new index" (/workspace/opencms-core/test/data/WEB-INF/index/Test new index).
    ( 50 ) Indexing file /sites/default/xmlcontent/article_0001.html ... 16 Mar 2018 18:56:01,073  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "en_spell[ defaultValue:null targetField:en_spell locale:en copyFields:null ]".
    16 Mar 2018 18:56:01,073  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "en_DE_spell[ defaultValue:null targetField:en_DE_spell locale:en_DE copyFields:null ]".
    16 Mar 2018 18:56:01,074  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "en_GB_spell[ defaultValue:null targetField:en_GB_spell locale:en_GB copyFields:null ]".
    16 Mar 2018 18:56:01,074  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "fr_spell[ defaultValue:null targetField:fr_spell locale:fr copyFields:null ]".
    16 Mar 2018 18:56:01,074  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "de_spell[ defaultValue:null targetField:de_spell locale:de copyFields:null ]".
    o.k.
    16 Mar 2018 18:56:01,075  INFO [search.solr.CmsSolrIndexWriter: 196] Updating document "/sites/default/xmlcontent/article_0001.html" in search index "Test new index" (/workspace/opencms-core/test/data/WEB-INF/index/Test new index).
    ( 51 ) Indexing file /sites/default/xmlcontent/article_0002.html ... 16 Mar 2018 18:56:01,106  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "en_spell[ defaultValue:null targetField:en_spell locale:en copyFields:null ]".
    16 Mar 2018 18:56:01,106  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "en_DE_spell[ defaultValue:null targetField:en_DE_spell locale:en_DE copyFields:null ]".
    16 Mar 2018 18:56:01,106  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "en_GB_spell[ defaultValue:null targetField:en_GB_spell locale:en_GB copyFields:null ]".
    16 Mar 2018 18:56:01,107  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "fr_spell[ defaultValue:null targetField:fr_spell locale:fr copyFields:null ]".
    16 Mar 2018 18:56:01,107  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "de_spell[ defaultValue:null targetField:de_spell locale:de copyFields:null ]".
    o.k.
    16 Mar 2018 18:56:01,108  INFO [search.solr.CmsSolrIndexWriter: 196] Updating document "/sites/default/xmlcontent/article_0002.html" in search index "Test new index" (/workspace/opencms-core/test/data/WEB-INF/index/Test new index).
    ( 52 ) Indexing file /sites/default/xmlcontent/article_0003.html ... 16 Mar 2018 18:56:01,122  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "en_spell[ defaultValue:null targetField:en_spell locale:en copyFields:null ]".
    16 Mar 2018 18:56:01,122  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "en_DE_spell[ defaultValue:null targetField:en_DE_spell locale:en_DE copyFields:null ]".
    16 Mar 2018 18:56:01,122  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "en_GB_spell[ defaultValue:null targetField:en_GB_spell locale:en_GB copyFields:null ]".
    16 Mar 2018 18:56:01,122  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "fr_spell[ defaultValue:null targetField:fr_spell locale:fr copyFields:null ]".
    16 Mar 2018 18:56:01,122  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "de_spell[ defaultValue:null targetField:de_spell locale:de copyFields:null ]".
    o.k.
    16 Mar 2018 18:56:01,123  INFO [search.solr.CmsSolrIndexWriter: 196] Updating document "/sites/default/xmlcontent/article_0003.html" in search index "Test new index" (/workspace/opencms-core/test/data/WEB-INF/index/Test new index).
    ( 53 ) Indexing file /sites/default/xmlcontent/article_0004.html ... 16 Mar 2018 18:56:01,132  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "en_spell[ defaultValue:null targetField:en_spell locale:en copyFields:null ]".
    16 Mar 2018 18:56:01,133  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "en_DE_spell[ defaultValue:null targetField:en_DE_spell locale:en_DE copyFields:null ]".
    16 Mar 2018 18:56:01,133  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "en_GB_spell[ defaultValue:null targetField:en_GB_spell locale:en_GB copyFields:null ]".
    16 Mar 2018 18:56:01,133  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "fr_spell[ defaultValue:null targetField:fr_spell locale:fr copyFields:null ]".
    16 Mar 2018 18:56:01,133  WARN [ms.search.solr.CmsSolrDocument: 254] No field defined in Solr schema for field: "de_spell[ defaultValue:null targetField:de_spell locale:de copyFields:null ]".
    o.k.
    16 Mar 2018 18:56:01,133  INFO [search.solr.CmsSolrIndexWriter: 196] Updating document "/sites/default/xmlcontent/article_0004.html" in search index "Test new index" (/workspace/opencms-core/test/data/WEB-INF/index/Test new index).
    16 Mar 2018 18:56:01,137  INFO [search.solr.CmsSolrIndexWriter: 118] Committing changes to search index "Test new index" (/workspace/opencms-core/test/data/WEB-INF/index/Test new index).
    ------ ... finished rebuilding search index "Test new index"
    Indexing statistics: indexed files: 53, returned threads: 53, abandoned threads: 0, duration: 00:00:00
    16 Mar 2018 18:56:01,264  INFO [earch.CmsIndexingThreadManager: 222] Indexing statistics: indexed files: 53, returned threads: 53, abandoned threads: 0, duration: 00:00:00
    #################################
    Found: 4
    Start: 0
    Max Score: 1.0
    Query: q=*:*&fl=*,score&qt=edismax&rows=10&fq=expired:[NOW TO *]&fq=released:[* TO NOW]&fq=search_exclude:"false"
    #################################
    1   /sites/default/xmlcontent/article_0001.html      article   18.10.04 18:59   score: 100
    2   /sites/default/xmlcontent/article_0002.html      article   19.10.04 18:59   score: 100
    3   /sites/default/xmlcontent/article_0003.html      article   20.10.04 19:00   score: 100
    4   /sites/default/xmlcontent/article_0004.html      article   21.10.04 19:00   score: 100
    16 Mar 2018 18:56:01,601  INFO [.opencms.search.CmsSearchIndex:1687] . Search index         : Index "Test new index" has been successfully shut down
    16 Mar 2018 18:56:01,618 ERROR [ache.solr.common.SolrException: 159] Error removing directory:java.io.IOException: Unable to delete directory /workspace/opencms-core/test/data/WEB-INF/index/Test new index/spellchecker.
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1623)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617)
        at org.apache.solr.core.StandardDirectoryFactory.removeDirectory(StandardDirectoryFactory.java:108)
        at org.apache.solr.core.CachingDirectoryFactory.close(CachingDirectoryFactory.java:207)
        at org.apache.solr.core.SolrCore.close(SolrCore.java:1633)
        at org.apache.solr.core.SolrCore.closeAndWait(SolrCore.java:1344)
        at org.apache.solr.core.CoreContainer.unload(CoreContainer.java:1404)
        at org.opencms.search.CmsSearchManager.removeSearchIndex(CmsSearchManager.java:1956)
        at org.opencms.search.solr.TestSolrSearch.testIndexGeneration(TestSolrSearch.java:390)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at junit.framework.TestCase.runTest(TestCase.java:176)
        at org.opencms.test.OpenCmsTestCase.runTest(OpenCmsTestCase.java:3812)
        at junit.framework.TestCase.runBare(TestCase.java:141)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:129)
        at junit.framework.TestSuite.runTest(TestSuite.java:255)
        at junit.framework.TestSuite.run(TestSuite.java:250)
        at junit.extensions.TestDecorator.basicRun(TestDecorator.java:23)
        at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.extensions.TestSetup.run(TestSetup.java:27)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:108)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by gallardo** [comment]
Lucene already acknowledged this problematic setting (see e.g. https://issues.apache.org/jira/browse/LUCENE-710), but unfortunately I could not find a solution using available tools. Given that this is an issue affecting a specific discouraged configuration, I'm closing it.
