### ISSUE TITLE
Store Session to Redis and Backoffice can not login

### ISSUE THREAD

**Issue by Blankchen** [alkacon/opencms-core#591]
**Version:** opencms-10.5.3
According to this https://github.com/redisson/redisson/wiki/2.-Configuration#261-single-instance-settings

The system/login page can not show, and get the following error
```
com.vaadin.server.DefaultErrorHandler.doDefault
 java.lang.NullPointerException
        at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:76)
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1422)
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:379)
        at org.opencms.main.CmsUIServlet.service(CmsUIServlet.java:321)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.opencms.main.OpenCmsUrlServletFilter.doFilter(OpenCmsUrlServletFilter.java:132)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by TommyYehCool** [comment]
It seems that CmsSystemConfiguration can set sessionStorageProvider.

Is there a class for storing the session at redis just modify config can do it or need to impelement ?

**Comment by tHerrmann** [comment]
Please explain in more detail what lead to this error. For example any specific configuration. And also explain what you are trying to achieve.

**Comment by Blankchen** [comment]
### In /var/lib/tomcat8/lib
redisson-all-3.6.4.jar 
redisson-tomcat-8-3.6.4.jar

### In /var/lib/tomcat8/webapps/ROOT/META-INF
context.xml
```
<?xml version='1.0' encoding='utf-8'?>
<Context>
        <Manager className="org.redisson.tomcat.RedissonSessionManager"
                 configPath="${catalina.base}/webapps/ROOT/META-INF/redisson.yaml"/>
</Context>
```
redisson.yaml 
```
singleServerConfig:
  address: "redis://XXXXXXXXXXXXXXXXXXX:6379"
  database: 4
```
### Achieve
The Opencms sessions are all in Redis database.
But the /system/login backoffice can not login any more.
I think is the session can not be read by opencms from backoffice....

**Comment by tHerrmann** [comment]
OpenCms sessions are not serializable. So I don't think this will work.
