### ISSUE TITLE
javax.servlet.jsp.JspException: org.opencms.xml.CmsXmlException: Resource "/system/modules/com.my.module/templates/my.template.jsp" is not of required type XML content.

### ISSUE THREAD

**Issue by snehal2** [alkacon/opencms-core#592]
" <%@ taglib prefix="cms" uri="http://www.opencms.org/taglib/cms"%> " for this first line in jsp page above error is coming.

**Comment by snehal2** [comment]
This is my jsp code....
<%@page buffer="none" session="false" trimDirectiveWhitespaces="true"%>
<%@ taglib prefix="cms" uri="http://www.opencms.org/taglib/cms"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<html>
<head>
<title><cms:info property="opencms.title" /></title>
<cms:enable-ade />  </head> 
<body>
<div id="header"> 
<cms:container name="headercontainer" type="header"/>   </div>
<div>
<img src="http://localhost:8080/opencms/system/modules/com.my.module/resources/images/Desert.jpg">
</div>
<div id="footer"> 
<cms:container name="footercontainer" type="footer"/>   </div>
</body>
</html>
-------------
Stack Trace...
An error occurred.<br />javax.servlet.jsp.JspException: org.opencms.xml.CmsXmlException: Resource "/system/modules/com.my.module/templates/my.template.jsp" is not of required type XML content.
javax.servlet.ServletException: javax.servlet.jsp.JspException: org.opencms.xml.CmsXmlException: Resource "/system/modules/com.my.module/templates/my.template.jsp" is not of required type XML content.
	at org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:905)
	at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:838) 	at org.apache.jsp.WEB_002dINF.jsp.offline.system.modules.com_my_module.templates.my_template_jsp._jspService(my_template_jsp.java:160)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:716)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523)
	at org.opencms.flex.CmsFlexRequestDispatcher.includeExternal(CmsFlexRequestDispatcher.java:191)
	at org.opencms.flex.CmsFlexRequestDispatcher.include(CmsFlexRequestDispatcher.java:165)
	at org.opencms.loader.CmsJspLoader.service(CmsJspLoader.java:666)
	at org.opencms.flex.CmsFlexRequestDispatcher.includeInternalWithCache(CmsFlexRequestDispatcher.java:441)
	at org.opencms.flex.CmsFlexRequestDispatcher.include(CmsFlexRequestDispatcher.java:169)
	at org.opencms.loader.CmsJspLoader.dispatchJsp(CmsJspLoader.java:988)
	at org.opencms.loader.CmsJspLoader.load(CmsJspLoader.java:538)
	at org.opencms.loader.CmsResourceManager.loadResource(CmsResourceManager.java:1194)
	at org.opencms.main.OpenCmsCore.showResource(OpenCmsCore.java:1796)
	at org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:161)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.opencms.jsp.jsonpart.CmsJsonPartFilter.doFilter(CmsJsonPartFilter.java:281)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:716)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at org.opencms.main.OpenCmsUrlServletFilter.doFilter(OpenCmsUrlServletFilter.java:127)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.opencms.xml.CmsXmlException: Resource "/system/modules/com.my.module/templates/my.template.jsp" is not of required type XML content.
	at org.opencms.xml.containerpage.CmsXmlContainerPageFactory.unmarshal(CmsXmlContainerPageFactory.java:344)
	at org.opencms.jsp.CmsJspTagContainer.doEndTag(CmsJspTagContainer.java:666)
	at org.apache.jsp.WEB_002dINF.jsp.offline.system.modules.com_my_module.templates.my_template_jsp._jspx_meth_cms_005fcontainer_005f0(my_template_jsp.java:229)
	at org.apache.jsp.WEB_002dINF.jsp.offline.system.modules.com_my_module.templates.my_template_jsp._jspService(my_template_jsp.java:137)
	... 54 more
