### ISSUE TITLE
NPE when copying page from language comparison

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#606]
In #build_10_5_4_1 cannot copy from language comparison. The site editor fails opening the path selector:

![image](https://user-images.githubusercontent.com/790448/45424195-0b8deb80-b696-11e8-810f-71d8730baea2.png)

To reproduce:

`Sitemap` > `Sprachvergleich` > `Seite kopieren` > Select folder

![image](https://user-images.githubusercontent.com/790448/45424019-7ab71000-b695-11e8-838c-7b2c15c57a2a.png)

Unfortunately there is no more info than the stack trace.

Server log:
```
com.vaadin.event.ListenerMethod$MethodException: Invocation of method nodeExpand in org.opencms.ui.components.fileselect.CmsResourceTreeTable$2 failed.
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:533)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1015)
	at com.vaadin.ui.TreeTable.fireExpandEvent(TreeTable.java:925)
	at com.vaadin.ui.TreeTable.toggleChildVisibility(TreeTable.java:588)
	at com.vaadin.ui.TreeTable.setCollapsed(TreeTable.java:841)
	at org.opencms.ui.components.fileselect.CmsResourceTreeTable.expandItem(CmsResourceTreeTable.java:317)
	at org.opencms.ui.components.fileselect.CmsResourceSelectDialog.openPath(CmsResourceSelectDialog.java:226)
	at org.opencms.ui.components.fileselect.A_CmsFileSelectField.openFileSelector(A_CmsFileSelectField.java:166)
	at org.opencms.ui.components.fileselect.A_CmsFileSelectField$1.buttonClick(A_CmsFileSelectField.java:140)
	at sun.reflect.GeneratedMethodAccessor502.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1015)
	at com.vaadin.ui.Button.fireClick(Button.java:377)
	at com.vaadin.ui.Button$1.click(Button.java:54)
	at sun.reflect.GeneratedMethodAccessor518.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:437)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:402)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380)
	at org.opencms.main.CmsUIServlet.service(CmsUIServlet.java:321)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at de.stuttgart.uni.mailtools.EmailObfuscatorFilter.doFilter(EmailObfuscatorFilter.java:78)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.StuckThreadDetectionValve.invoke(StuckThreadDetectionValve.java:206)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.opencms.ui.components.fileselect.CmsResourceTreeContainer.fillProperties(CmsResourceTreeContainer.java:294)
	at org.opencms.ui.components.fileselect.CmsResourceTreeContainer.addTreeItem(CmsResourceTreeContainer.java:112)
	at org.opencms.ui.components.fileselect.CmsResourceTreeContainer.readTreeLevel(CmsResourceTreeContainer.java:166)
	at org.opencms.ui.components.fileselect.CmsResourceTreeTable$2.nodeExpand(CmsResourceTreeTable.java:258)
	at sun.reflect.GeneratedMethodAccessor472.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	... 57 more
```

**Comment by gallardo** [comment]
Trying to reproduce this issue in a simplified site, I'm getting another NPE. The GUI doesn't provide any info, just an empty dialog.

Steps:

1. Create following folder structure:
```
opencms-606
\-- de [locale = de; locale-available = de,en]
    +-- .content
    +-- page
    |   \-- index.html
    \-- en [locale = en; locale-available = de,en]
         +-- .content
```
![image](https://user-images.githubusercontent.com/790448/45514806-b4c40700-b7a6-11e8-8568-99c4ce6099df.png)

2. Open the sitemap editor under `opencms-606/de`
3. Invoke language comparison -> The GUI shows an empty box:

![image](https://user-images.githubusercontent.com/790448/45514741-83e3d200-b7a6-11e8-8939-77d55ee705e5.png)

This error is written to the logs:

```
13 Sep 2018 22:35:13,626 ERROR [map.CmsSitemapTreeDataProvider: 198] 
java.lang.NullPointerException
	at org.opencms.i18n.CmsLocaleGroupService.readLocaleGroup(CmsLocaleGroupService.java:492)
	at org.opencms.ui.sitemap.CmsSitemapTreeNodeData.initialize(CmsSitemapTreeNodeData.java:148)
	at org.opencms.ui.sitemap.CmsSitemapTreeDataProvider.getData(CmsSitemapTreeDataProvider.java:195)
	at org.opencms.ui.sitemap.CmsSitemapTreeDataProvider.getRoot(CmsSitemapTreeDataProvider.java:211)
	at org.opencms.ui.sitemap.CmsSitemapTreeController.createRootNode(CmsSitemapTreeController.java:1061)
	at org.opencms.ui.sitemap.CmsLocaleComparePanel.initTree(CmsLocaleComparePanel.java:383)
	at org.opencms.ui.sitemap.CmsLocaleComparePanel.initialize(CmsLocaleComparePanel.java:310)
	at org.opencms.ui.sitemap.CmsLocaleComparePanel.<init>(CmsLocaleComparePanel.java:111)
	at org.opencms.ui.sitemap.CmsSitemapExtension.showLocaleComparison(CmsSitemapExtension.java:387)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:437)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:402)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380)
	at org.opencms.main.CmsUIServlet.service(CmsUIServlet.java:321)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at de.stuttgart.uni.mailtools.EmailObfuscatorFilter.doFilter(EmailObfuscatorFilter.java:78)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.StuckThreadDetectionValve.invoke(StuckThreadDetectionValve.java:206)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
13 Sep 2018 22:35:13,628 ERROR [din.server.DefaultErrorHandler:  58] 
java.lang.NullPointerException
	at org.opencms.ui.sitemap.CmsSitemapTreeController.createNode(CmsSitemapTreeController.java:957)
	at org.opencms.ui.sitemap.CmsSitemapTreeController.createRootNode(CmsSitemapTreeController.java:1061)
	at org.opencms.ui.sitemap.CmsLocaleComparePanel.initTree(CmsLocaleComparePanel.java:383)
	at org.opencms.ui.sitemap.CmsLocaleComparePanel.initialize(CmsLocaleComparePanel.java:310)
	at org.opencms.ui.sitemap.CmsLocaleComparePanel.<init>(CmsLocaleComparePanel.java:111)
	at org.opencms.ui.sitemap.CmsSitemapExtension.showLocaleComparison(CmsSitemapExtension.java:387)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:437)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:402)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380)
	at org.opencms.main.CmsUIServlet.service(CmsUIServlet.java:321)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at de.stuttgart.uni.mailtools.EmailObfuscatorFilter.doFilter(EmailObfuscatorFilter.java:78)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.StuckThreadDetectionValve.invoke(StuckThreadDetectionValve.java:206)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gallardo** [comment]
Progressing: this last error seems to be caused by opencms expecting a page under the `opencms-606/de` subsite folder. Creating a container page `opencms-606/de/index.html` solves this last error.

**Comment by gallardo** [comment]
Activating warning for `CmsJspNavBuilder` I'm getting a permissions problem that I cannot understand: there is indeed a site `/sites/default/ze/archiv/`, but my test site is in a completely different path and it seems completely unrelated. Furhtermore, I have edited the site configuration to deactivate all inherited configuration.

```
13 Sep 2018 23:26:20,343  WARN [g.opencms.jsp.CmsJspNavBuilder: 770] Fehler beim Lesen der Ressource aus dem Pfad "/sites/default/ze/archiv/".
org.opencms.security.CmsPermissionViolationException: Fehler beim Lesen der Ressource aus dem Pfad "/sites/default/ze/archiv/".
	at org.opencms.security.CmsPermissionViolationException.createException(CmsPermissionViolationException.java:71)
	at org.opencms.db.CmsDbContext.throwException(CmsDbContext.java:335)
	at org.opencms.db.CmsDbContext.report(CmsDbContext.java:287)
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:5051)
	at org.opencms.file.CmsObject.readResource(CmsObject.java:3214)
	at org.opencms.jsp.CmsJspNavBuilder.getNavigationForResource(CmsJspNavBuilder.java:735)
	at org.opencms.jsp.CmsJspNavBuilder.getNavigationForResource(CmsJspNavBuilder.java:529)
	at org.opencms.ui.components.fileselect.CmsResourceTreeContainer.fillProperties(CmsResourceTreeContainer.java:291)
	at org.opencms.ui.components.fileselect.CmsResourceTreeContainer.addTreeItem(CmsResourceTreeContainer.java:112)
	at org.opencms.ui.components.fileselect.CmsResourceTreeContainer.readTreeLevel(CmsResourceTreeContainer.java:166)
	at org.opencms.ui.components.fileselect.CmsResourceTreeTable$2.nodeExpand(CmsResourceTreeTable.java:258)
	at sun.reflect.GeneratedMethodAccessor466.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1015)
	at com.vaadin.ui.TreeTable.fireExpandEvent(TreeTable.java:925)
	at com.vaadin.ui.TreeTable.toggleChildVisibility(TreeTable.java:588)
	at com.vaadin.ui.TreeTable.setCollapsed(TreeTable.java:841)
	at org.opencms.ui.components.fileselect.CmsResourceTreeTable.expandItem(CmsResourceTreeTable.java:317)
	at org.opencms.ui.components.fileselect.CmsResourceSelectDialog.openPath(CmsResourceSelectDialog.java:226)
	at org.opencms.ui.components.fileselect.A_CmsFileSelectField.openFileSelector(A_CmsFileSelectField.java:166)
	at org.opencms.ui.components.fileselect.A_CmsFileSelectField$1.buttonClick(A_CmsFileSelectField.java:140)
	at sun.reflect.GeneratedMethodAccessor523.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1015)
	at com.vaadin.ui.Button.fireClick(Button.java:377)
	at com.vaadin.ui.Button$1.click(Button.java:54)
	at sun.reflect.GeneratedMethodAccessor537.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:437)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:402)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380)
	at org.opencms.main.CmsUIServlet.service(CmsUIServlet.java:321)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at de.stuttgart.uni.mailtools.EmailObfuscatorFilter.doFilter(EmailObfuscatorFilter.java:78)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.StuckThreadDetectionValve.invoke(StuckThreadDetectionValve.java:206)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.opencms.security.CmsPermissionViolationException: Zugriff zur Ressource "/sites/default/ze/archiv/" verweigert. Sie benötigen die Zugriffsrechte "+r".
	at org.opencms.db.CmsSecurityManager.checkPermissions(CmsSecurityManager.java:7053)
	at org.opencms.db.CmsSecurityManager.checkPermissions(CmsSecurityManager.java:7023)
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:7466)
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:5049)
	... 68 more
```
