### ISSUE TITLE
'org.apache.solr.common.SolrException' in CmsPublishThread

### ISSUE THREAD

**Issue by ByungJun25** [alkacon/opencms-core#615]
Hello,

I got a exception error when I publish any content from offline to online.
Eventhough I got a exception error, but I could publish the content anyway. And there was no problem to see the contents on online Site.

Log is like as below.
***
ERROR [ache.solr.common.SolrException: 148] [org.apache.solr.handler.RequestHandlerBase] [C7AB83A46B4D541922FDC31791A7173C] [-1] org.apache.solr.common.SolrException: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at org.apache.solr.core.SolrCore.getSearcher(SolrCore.java:1944)
	at org.apache.solr.core.SolrCore.getSearcher(SolrCore.java:1553)
	at org.apache.solr.update.DirectUpdateHandler2.commit(DirectUpdateHandler2.java:650)
	at org.apache.solr.update.processor.RunUpdateProcessor.processCommit(RunUpdateProcessorFactory.java:94)
	at org.apache.solr.update.processor.UpdateRequestProcessor.processCommit(UpdateRequestProcessor.java:61)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalCommit(DistributedUpdateProcessor.java:1628)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.processCommit(DistributedUpdateProcessor.java:1605)
	at org.apache.solr.handler.RequestHandlerUtils.handleCommit(RequestHandlerUtils.java:68)
	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:63)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2102)
	at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:178)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
	at org.apache.solr.client.solrj.SolrClient.commit(SolrClient.java:482)
	at org.apache.solr.client.solrj.SolrClient.commit(SolrClient.java:463)
	at org.opencms.search.solr.CmsSolrIndexWriter.commit(CmsSolrIndexWriter.java:121)
	at org.opencms.search.CmsSearchManager.updateIndexIncremental(CmsSearchManager.java:2985)
	at org.opencms.search.CmsSearchManager.updateIndex(CmsSearchManager.java:2881)
	at org.opencms.search.CmsSearchManager.updateAllIndexes(CmsSearchManager.java:2702)
	at org.opencms.search.CmsSearchManager.cmsEvent(CmsSearchManager.java:1010)
	at org.opencms.main.CmsEventManager.fireEventHandler(CmsEventManager.java:194)
	at org.opencms.main.CmsEventManager.fireEvent(CmsEventManager.java:117)
	at org.opencms.main.OpenCms.fireCmsEvent(OpenCms.java:157)
	at org.opencms.publish.CmsPublishEngine.publishJobFinished(CmsPublishEngine.java:657)
	at org.opencms.publish.CmsPublishThread.run(CmsPublishThread.java:180)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.execute(ExecutorUtil.java:194)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.apache.solr.core.SolrCore.getSearcher(SolrCore.java:1847)
	... 24 more

ERROR [encms.publish.CmsPublishEngine: 662] [org.opencms.publish.CmsPublishEngine] [C7AB83A46B4D541922FDC31791A7173C] [-1] java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
org.apache.solr.common.SolrException: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at org.apache.solr.core.SolrCore.getSearcher(SolrCore.java:1944)
	at org.apache.solr.core.SolrCore.getSearcher(SolrCore.java:1553)
	at org.apache.solr.update.DirectUpdateHandler2.commit(DirectUpdateHandler2.java:650)
	at org.apache.solr.update.processor.RunUpdateProcessor.processCommit(RunUpdateProcessorFactory.java:94)
	at org.apache.solr.update.processor.UpdateRequestProcessor.processCommit(UpdateRequestProcessor.java:61)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalCommit(DistributedUpdateProcessor.java:1628)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.processCommit(DistributedUpdateProcessor.java:1605)
	at org.apache.solr.handler.RequestHandlerUtils.handleCommit(RequestHandlerUtils.java:68)
	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:63)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2102)
	at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:178)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
	at org.apache.solr.client.solrj.SolrClient.commit(SolrClient.java:482)
	at org.apache.solr.client.solrj.SolrClient.commit(SolrClient.java:463)
	at org.opencms.search.solr.CmsSolrIndexWriter.commit(CmsSolrIndexWriter.java:121)
	at org.opencms.search.CmsSearchManager.updateIndexIncremental(CmsSearchManager.java:2985)
	at org.opencms.search.CmsSearchManager.updateIndex(CmsSearchManager.java:2881)
	at org.opencms.search.CmsSearchManager.updateAllIndexes(CmsSearchManager.java:2702)
	at org.opencms.search.CmsSearchManager.cmsEvent(CmsSearchManager.java:1010)
	at org.opencms.main.CmsEventManager.fireEventHandler(CmsEventManager.java:194)
	at org.opencms.main.CmsEventManager.fireEvent(CmsEventManager.java:117)
	at org.opencms.main.OpenCms.fireCmsEvent(OpenCms.java:157)
	at org.opencms.publish.CmsPublishEngine.publishJobFinished(CmsPublishEngine.java:657)
	at org.opencms.publish.CmsPublishThread.run(CmsPublishThread.java:180)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.execute(ExecutorUtil.java:194)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.apache.solr.core.SolrCore.getSearcher(SolrCore.java:1847)
	... 24 more

***

I guess some setting value is wrong.. but I can't find which config file was related. And also I couldn't use search function since I got this error message.

***
Version and Build Information is like as below

Version: 10.5.3
Build Date: 2017-10-18 11:07
Git Branch: build_10_5_3
Git Commit ID: d5e099d
Build Number: #1377
Build System: Jenkins ci-release
Build Type: Release

Thank you.

**Comment by ByungJun25** [comment]
Hi guys,

I found when this error will be occured. This error will be occured in the case like below.

- When the old and new workspaces are open together and Index's rebuild mode is auto.

And I get the new error log message now.

> Calling event listener "org.opencms.search.CmsSearchManager" failed for "CmsEvent['2']".

I guess, the rebuilding of index is faild when the user publishes the resource. Because after I just changed the property value and published the resource(Of course, in this time I got the same error), the solr system didn't show the new value of property.

I still not found the solution and I didn't understand what CmsEvent['2'] means.
I need to solve this problem, because i don't want to rebuild manually everyday...

Could you help me?

Thank you.

Best Regard,
Byungjun Woo
