### ISSUE TITLE
OpenCms 11 beta issue

### ISSUE THREAD

**Issue by superc** [alkacon/opencms-core#619]
![opencms_11_beta_20181206153540](https://user-images.githubusercontent.com/3608960/49569065-daa81480-f96d-11e8-8d37-52321aeeb1d1.png)

**Comment by tHerrmann** [comment]
This works for me. Could you provide the requested URL for this resource?

Also, are you running OpenCms within Tomcat or another Servlet-Container?

**Comment by tHerrmann** [comment]
This looks alright. We haven't changed the way this URL is generated for ages and never had any issues. Do you get anything in the Tomcat log files, showing why this is treated as a 'Bad request' with status 400?

**Comment by superc** [comment]
```
06-Dec-2018 16:20:19.551 INFO [http-nio-8080-exec-6] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Request header is too large
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:702)
	at org.apache.coyote.http11.Http11InputBuffer.parseHeader(Http11InputBuffer.java:848)
	at org.apache.coyote.http11.Http11InputBuffer.parseHeaders(Http11InputBuffer.java:561)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:699)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

06-Dec-2018 16:20:49.270 INFO [http-nio-8080-exec-4] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Request header is too large
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:702)
	at org.apache.coyote.http11.Http11InputBuffer.parseHeader(Http11InputBuffer.java:848)
	at org.apache.coyote.http11.Http11InputBuffer.parseHeaders(Http11InputBuffer.java:561)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:699)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by tHerrmann** [comment]
You need to reconfigure tomcat and set server.tomcat.max-http-header-size to a higher value to avoid this issue.

**Comment by superc** [comment]
All right after configuation server.xml

```
    <Connector port="8080" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443"
               maxHttpHeaderSize="18192"
	/>
```
