### ISSUE TITLE
OpenCms 11 RC: Logfile content not shown in Workplace

### ISSUE THREAD

**Issue by veggie4ever** [alkacon/opencms-core#639]
The content of the selected Logfile is not shown in the workplace:
![ocms11rc-logfile-not-shown](https://user-images.githubusercontent.com/3355835/56722840-20f8e700-6748-11e9-8bd2-6567af59fad0.png)
The area, where the log file content should be shown is empty.
Selecting another logfile and / or reloading the log does not help. Downloading the logfile works fine.
There is an exception in the log:
```
25 Apr. 2019 10:49:01,145 ERROR [ui.apps.logfile.CmsLogFileView: 205] Impossible to read from the file "C:\Users\username\e_ws\ws.ocms11\apache-tomcat-8.5.39\webapps\opencms\WEB-INF\logs\opencms.log".
org.opencms.util.CmsRfsException: Impossible to read from the file "C:\Users\username\e_ws\ws.ocms11\apache-tomcat-8.5.39\webapps\opencms\WEB-INF\logs\opencms.log".
	at org.opencms.util.CmsRfsFileViewer.setFilePath(CmsRfsFileViewer.java:446) ~[opencms.jar:11.0.0_rc]
	at org.opencms.ui.apps.logfile.CmsLogFileView.updateView(CmsLogFileView.java:196) [opencms.jar:11.0.0_rc]
	at org.opencms.ui.apps.logfile.CmsLogFileView.<init>(CmsLogFileView.java:169) [opencms.jar:11.0.0_rc]
	at org.opencms.ui.apps.logfile.CmsLogFileApp.getComponentForState(CmsLogFileApp.java:180) [opencms.jar:11.0.0_rc]
	at org.opencms.ui.apps.A_CmsWorkplaceApp.openSubView(A_CmsWorkplaceApp.java:297) [opencms.jar:11.0.0_rc]
	at org.opencms.ui.apps.A_CmsWorkplaceApp.onStateChange(A_CmsWorkplaceApp.java:283) [opencms.jar:11.0.0_rc]
	at org.opencms.ui.apps.CmsAppView.enter(CmsAppView.java:240) [opencms.jar:11.0.0_rc]
	at org.opencms.ui.apps.CmsAppView.enter(CmsAppView.java:253) [opencms.jar:11.0.0_rc]
	at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:778) [vaadin-server-8.4.1.jar:8.4.1]
	at com.vaadin.navigator.Navigator.lambda$navigateTo$9a874efd$1(Navigator.java:702) [vaadin-server-8.4.1.jar:8.4.1]
	at com.vaadin.navigator.ViewBeforeLeaveEvent.navigate(ViewBeforeLeaveEvent.java:54) [vaadin-server-8.4.1.jar:8.4.1]
	at com.vaadin.navigator.View.beforeLeave(View.java:79) [vaadin-server-8.4.1.jar:8.4.1]
	at com.vaadin.navigator.Navigator.runAfterLeaveConfirmation(Navigator.java:730) [vaadin-server-8.4.1.jar:8.4.1]
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:701) [vaadin-server-8.4.1.jar:8.4.1]
	at org.opencms.ui.apps.CmsAppNavigator.navigateTo(CmsAppNavigator.java:65) [opencms.jar:11.0.0_rc]
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:678) [vaadin-server-8.4.1.jar:8.4.1]
	at org.opencms.ui.apps.CmsAppWorkplaceUi.showApp(CmsAppWorkplaceUi.java:481) [opencms.jar:11.0.0_rc]
	at org.opencms.ui.apps.CmsDefaultAppButtonProvider$1.buttonClick(CmsDefaultAppButtonProvider.java:80) [opencms.jar:11.0.0_rc]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499) [vaadin-server-8.4.1.jar:8.4.1]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273) [vaadin-server-8.4.1.jar:8.4.1]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237) [vaadin-server-8.4.1.jar:8.4.1]
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1014) [vaadin-server-8.4.1.jar:8.4.1]
	at com.vaadin.ui.Button.fireClick(Button.java:384) [vaadin-server-8.4.1.jar:8.4.1]
	at com.vaadin.ui.Button$1.click(Button.java:57) [vaadin-server-8.4.1.jar:8.4.1]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155) [vaadin-server-8.4.1.jar:8.4.1]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116) [vaadin-server-8.4.1.jar:8.4.1]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445) [vaadin-server-8.4.1.jar:8.4.1]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410) [vaadin-server-8.4.1.jar:8.4.1]
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274) [vaadin-server-8.4.1.jar:8.4.1]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90) [vaadin-server-8.4.1.jar:8.4.1]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) [vaadin-server-8.4.1.jar:8.4.1]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1601) [vaadin-server-8.4.1.jar:8.4.1]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:445) [vaadin-server-8.4.1.jar:8.4.1]
	at org.opencms.main.CmsUIServlet.service(CmsUIServlet.java:328) [opencms.jar:11.0.0_rc]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.39]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.39]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.39]
	at org.opencms.main.OpenCmsUrlServletFilter.doFilter(OpenCmsUrlServletFilter.java:132) [opencms.jar:11.0.0_rc]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.39]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:8.5.39]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.39]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [catalina.jar:8.5.39]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) [catalina.jar:8.5.39]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.39]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) [catalina.jar:8.5.39]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.39]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:8.5.39]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) [tomcat-coyote.jar:8.5.39]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.39]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-coyote.jar:8.5.39]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-coyote.jar:8.5.39]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.39]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.39]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

- Windows 10
- OpenJDK 11
- Tomcat 8.5
- OpenCms 11 RC

**Comment by tHerrmann** [comment]
This seems to be a bug when running OpenCms on a Windows host system. We will fix it for the coming release.

**Comment by veggie4ever** [comment]
Great thanks.

**Comment by gWestenberger** [comment]
Fixed in branch_11_0_x.
