### ISSUE TITLE
OpenCms 11: Error displaying list

### ISSUE THREAD

**Issue by mfonolleda** [alkacon/opencms-core#656]
Hi, 

We are having issues displaying a list in a multilingual website using the multi tree approach. The error is as follows, any idea on what may be the issue?.

```
Execution of query "q={!tag=q type=edismax qf="content_ca Title_prop Description_dprop Description.html_dprop spell"}*&fl=path,instancedate_ca_dt,instancedateend_ca_dt,instancedatecurrenttill_ca_dt,id,solr_id,disptitle_ca_sort,link,type&qt=edismax&rows=400&fq=expired:[NOW TO *]&fq=released:[* TO NOW]&fq=parent-folders:("/sites/default/.content/m-article/")&fq=type:("m-article")&fq=category_exact:("Topic/Technology/")&fq=search_exclude:"false"&TZ=Europe/Berlin&start=0&sort=disporder_ca_i asc&facet=true&facet.field={!key=parent-folders facet.mincount=1 facet.limit=200 facet.sort=index ex=parent-folders,category_exact,instancedate,q}parent-folders&facet.field={!key=category_exact facet.mincount=1 facet.limit=200 facet.sort=index ex=parent-folders,category_exact,instancedate,q}category_exact&facet.range={!key=instancedate facet.range.start=NOW/YEAR-20YEARS facet.range.end=NOW/MONTH 2YEARS facet.range.gap= 1MONTHS facet.range.hardend=false facet.mincount=1 ex=parent-folders,category_exact,instancedate,q}instancedate_ca_dt" failed.

org.opencms.search.CmsSearchException: Execution of query "q={!tag=q type=edismax qf="content_ca Title_prop Description_dprop Description.html_dprop spell"}*&fl=path,instancedate_ca_dt,instancedateend_ca_dt,instancedatecurrenttill_ca_dt,id,solr_id,disptitle_ca_sort,link,type&qt=edismax&rows=400&fq=expired:[NOW TO *]&fq=released:[* TO NOW]&fq=parent-folders:("/sites/default/.content/m-article/")&fq=type:("m-article")&fq=category_exact:("Topic/Technology/")&fq=search_exclude:"false"&TZ=Europe/Berlin&start=0&sort=disporder_ca_i asc&facet=true&facet.field={!key=parent-folders facet.mincount=1 facet.limit=200 facet.sort=index ex=parent-folders,category_exact,instancedate,q}parent-folders&facet.field={!key=category_exact facet.mincount=1 facet.limit=200 facet.sort=index ex=parent-folders,category_exact,instancedate,q}category_exact&facet.range={!key=instancedate facet.range.start=NOW/YEAR-20YEARS facet.range.end=NOW/MONTH 2YEARS facet.range.gap= 1MONTHS facet.range.hardend=false facet.mincount=1 ex=parent-folders,category_exact,instancedate,q}instancedate_ca_dt" failed.
	at org.opencms.search.solr.CmsSolrIndex.search(CmsSolrIndex.java:1265)
	at org.opencms.search.solr.CmsSolrIndex.search(CmsSolrIndex.java:800)
	at org.opencms.search.solr.CmsSolrIndex.search(CmsSolrIndex.java:772)
	at org.opencms.ui.apps.lists.CmsListManager.executeSearch(CmsListManager.java:2114)
	at org.opencms.ui.apps.lists.CmsListManager.search(CmsListManager.java:1597)
	at org.opencms.ui.apps.lists.CmsListManager.search(CmsListManager.java:1537)
	at org.opencms.ui.apps.lists.CmsListManager.getComponentForState(CmsListManager.java:1658)
	at org.opencms.ui.apps.A_CmsWorkplaceApp.openSubView(A_CmsWorkplaceApp.java:297)
	at org.opencms.ui.apps.A_CmsWorkplaceApp.onStateChange(A_CmsWorkplaceApp.java:283)
	at org.opencms.ui.apps.lists.CmsListManager.onStateChange(CmsListManager.java:1463)
	at org.opencms.ui.apps.CmsAppView.enter(CmsAppView.java:240)
	at org.opencms.ui.apps.CmsAppView.enter(CmsAppView.java:253)
	at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:778)
	at com.vaadin.navigator.Navigator.lambda$navigateTo$9a874efd$1(Navigator.java:702)
	at com.vaadin.navigator.ViewBeforeLeaveEvent.navigate(ViewBeforeLeaveEvent.java:54)
	at com.vaadin.navigator.View.beforeLeave(View.java:79)
	at com.vaadin.navigator.Navigator.runAfterLeaveConfirmation(Navigator.java:730)
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:701)
	at org.opencms.ui.apps.CmsAppNavigator.navigateTo(CmsAppNavigator.java:65)
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:678)
	at org.opencms.ui.apps.CmsAppWorkplaceUi.showApp(CmsAppWorkplaceUi.java:492)
	at org.opencms.ui.actions.CmsDisplayAction.executeAction(CmsDisplayAction.java:75)
	at org.opencms.ui.actions.CmsContextMenuActionItem.executeAction(CmsContextMenuActionItem.java:79)
	at org.opencms.ui.contextmenu.CmsResourceContextMenuBuilder$1.contextMenuItemClicked(CmsResourceContextMenuBuilder.java:153)
	at org.opencms.ui.contextmenu.CmsContextMenu$ContextMenuItem.notifyClickListeners(CmsContextMenu.java:442)
	at org.opencms.ui.contextmenu.CmsContextMenu$1.itemClicked(CmsContextMenu.java:914)
	at jdk.internal.reflect.GeneratedMethodAccessor143.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1602)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:445)
	at org.opencms.main.CmsUIServlet.service(CmsUIServlet.java:328)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.opencms.main.OpenCmsUrlServletFilter.doFilter(OpenCmsUrlServletFilter.java:132)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1839)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: Query Field 'content_ca' is not a valid field name
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:216)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:272)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:199)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2559)
	at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:191)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:207)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:987)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:1002)
	at org.opencms.search.solr.CmsSolrIndex.search(CmsSolrIndex.java:996)
	... 61 more
Caused by: org.apache.solr.search.SyntaxError: Query Field 'content_ca' is not a valid field name
	at org.apache.solr.search.ExtendedDismaxQParser.checkFieldInSchema(ExtendedDismaxQParser.java:275)
	at org.apache.solr.search.ExtendedDismaxQParser.checkFieldsInSchema(ExtendedDismaxQParser.java:287)
	at org.apache.solr.search.ExtendedDismaxQParser.validateQueryFields(ExtendedDismaxQParser.java:226)
	at org.apache.solr.search.ExtendedDismaxQParser.parse(ExtendedDismaxQParser.java:151)
	at org.apache.solr.search.QParser.getQuery(QParser.java:173)
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:158)
	... 69 more
Caused by: org.apache.solr.common.SolrException: undefined field: "content_ca"
	at org.apache.solr.schema.IndexSchema.getField(IndexSchema.java:1234)
	at org.apache.solr.search.ExtendedDismaxQParser.checkFieldInSchema(ExtendedDismaxQParser.java:273)
	... 74 more
```

**Comment by dSeidel** [comment]
Hi,

you have a locale "ca", but you do not have added dynamic fields "*_ca" in your schema.xml for Solr. If you add a locale, you need to add the corresponding Solr fields in the schema.xml (e.g., lookup "de" or "it" to see what is necessary).

To your current problem: Solr says the field content_ca is unknown. Which is true, since you need to add it as describe above.

Best, Daniel.

**Comment by mfonolleda** [comment]
Hi Daniel, thanks for your help.

Which schema.xml for Solr are you referring to?

**Comment by mfonolleda** [comment]
Are you referring to webapps/ROOT/WEB-INF/solr/configsets/default/conf/schema.xml?

**Comment by dSeidel** [comment]
YesAm 07.06.2019 4:35 nachm. schrieb Miquel Fonolleda <notifications@github.com>:Are you referring to webapps/ROOT/WEB-INF/solr/configsets/default/conf/schema.xml?

**Comment by mfonolleda** [comment]
Solved. Thanks again!
