### ISSUE TITLE
Sheduled publish doesn't work

### ISSUE THREAD

**Issue by filipkratochvil** [alkacon/opencms-core#659]
Hi guys,
function "Publish scheduled" doesn't work in OpenCms 11.0.0 (latest).

Example:
- create some test file in Explorer
- right click on the file and select "Publish scheduled"
- select some date in the future and click "OK"
- bang, nothing happens...

You can see exclamation mark after clicking on the "OK" button and than exception in the log.
`
04 Jul 2019 16:43:29,265 ERROR [din.server.DefaultErrorHandler:  58] 
java.lang.NullPointerException: null
04 Jul 2019 16:43:29,271 ERROR [encms.ui.CmsVaadinErrorHandler:  80] Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:159) ~[vaadin-server-8.7.1.jar:8.7.1]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116) ~[vaadin-server-8.7.1.jar:8.7.1]
    at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445) [vaadin-server-8.7.1.jar:8.7.1]
    at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410) [vaadin-server-8.7.1.jar:8.7.1]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274) [vaadin-server-8.7.1.jar:8.7.1]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90) [vaadin-server-8.7.1.jar:8.7.1]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) [vaadin-server-8.7.1.jar:8.7.1]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1602) [vaadin-server-8.7.1.jar:8.7.1]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:445) [vaadin-server-8.7.1.jar:8.7.1]
    at org.opencms.main.CmsUIServlet.service(CmsUIServlet.java:328) [opencms.jar:11.0.0]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.13]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.13]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.13]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.13]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.13]
    at org.opencms.main.OpenCmsUrlServletFilter.doFilter(OpenCmsUrlServletFilter.java:132) [opencms.jar:11.0.0]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.13]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.13]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:9.0.13]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.13]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [catalina.jar:9.0.13]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.13]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.13]
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668) [catalina.jar:9.0.13]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.13]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.13]
    at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:394) [tomcat-coyote.jar:9.0.13]
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:9.0.13]
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791) [tomcat-coyote.jar:9.0.13]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417) [tomcat-coyote.jar:9.0.13]
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.13]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.13]
    at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
    at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155) ~[vaadin-server-8.7.1.jar:8.7.1]
    ... 35 more
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method buttonClick in org.opencms.ui.dialogs.CmsPublishScheduledDialog$1 failed.
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:519) ~[vaadin-server-8.7.1.jar:8.7.1]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273) ~[vaadin-server-8.7.1.jar:8.7.1]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237) ~[vaadin-server-8.7.1.jar:8.7.1]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1014) ~[vaadin-server-8.7.1.jar:8.7.1]
    at com.vaadin.ui.Button.fireClick(Button.java:384) ~[vaadin-server-8.7.1.jar:8.7.1]
    at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-8.7.1.jar:8.7.1]
    at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155) ~[vaadin-server-8.7.1.jar:8.7.1]
    ... 35 more
Caused by: java.lang.NullPointerException
`

**Comment by dSeidel** [comment]
Hi @filipkratochvil ,

I could reproduce the bug. It will be fixed in the next minor release. 

To get publish sheduled working in the current OpenCms version, you could add the action class "org.opencms.workplace.CmsWorkplaceAction" to one of the modules. Restart and it should work.

**Comment by filipkratochvil** [comment]
It works, thank you @dSeidel

**Comment by gWestenberger** [comment]
Fixed in branch_11_0_x.
