### ISSUE TITLE
Errors when creating/editing some VFS configuration files

### ISSUE THREAD

**Issue by filipkratochvil** [alkacon/opencms-core#670]
Hello,
we found some errors in log file when we create following vfs configuration files:
- Fomatter configuration (type: formatter_config, id: 308)
- Property resource bundle (type: propertyvfsbundle, id: 307)

It's not a big problem because it's working (probably) and older "property resource bundle" is not widely used anymore.

OpenCms 11.0.1 (upgraded from OpenCms 11.0.0).

**Formatter configuration**
`10 Sep 2019 11:02:02,094 ERROR [CmsFormatterConfigurationCache: 350] Error while trying to read formatter configuration /sites/default/new_formatter_config:    Neither container types nor c
ontainer widths defined!
org.opencms.ade.configuration.formatters.CmsFormatterBeanParser$ParseException: Neither container types nor container widths defined!
        at org.opencms.ade.configuration.formatters.CmsFormatterBeanParser.parseMatch(CmsFormatterBeanParser.java:773) ~[opencms.jar:11.0.1]
        at org.opencms.ade.configuration.formatters.CmsFormatterBeanParser.parse(CmsFormatterBeanParser.java:464) ~[opencms.jar:11.0.1]
        at org.opencms.ade.configuration.formatters.CmsFormatterConfigurationCache.readFormatter(CmsFormatterConfigurationCache.java:343) [opencms.jar:11.0.1]
        at org.opencms.ade.configuration.formatters.CmsFormatterConfigurationCache.performUpdate(CmsFormatterConfigurationCache.java:217) [opencms.jar:11.0.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

Problem occurs :
- when i create new file
- when i'll add container type/width to the existing document, than save, edit, remove and again save document

**Property resource bundle**
`10 Sep 2019 11:02:15,167 ERROR [le.CmsMessageBundleEditorTypes: 990] Searching for the bundle descriptor failed.
org.opencms.search.CmsSearchException: Execution of query "q=*:*&fl=*,score&fl=path&qt=edismax&rows=10&fq=filename:"new_propertyvfsbundle_desc"" failed.
        at org.opencms.search.solr.CmsSolrIndex.search(CmsSolrIndex.java:1265) ~[opencms.jar:11.0.1]
        at org.opencms.search.solr.CmsSolrIndex.search(CmsSolrIndex.java:800) ~[opencms.jar:11.0.1]
        at org.opencms.ui.editors.messagebundle.CmsMessageBundleEditorTypes.getDescriptor(CmsMessageBundleEditorTypes.java:988) [opencms.jar:11.0.1]
        at org.opencms.ui.editors.messagebundle.CmsMessageBundleEditorModel.initDescriptor(CmsMessageBundleEditorModel.java:1332) [opencms.jar:11.0.1]
        at org.opencms.ui.editors.messagebundle.CmsMessageBundleEditorModel.<init>(CmsMessageBundleEditorModel.java:546) [opencms.jar:11.0.1]
        at org.opencms.ui.editors.messagebundle.CmsMessageBundleEditor.initUI(CmsMessageBundleEditor.java:403) [opencms.jar:11.0.1]
        at org.opencms.ui.apps.CmsEditor.onStateChange(CmsEditor.java:295) [opencms.jar:11.0.1]
        at org.opencms.ui.apps.CmsAppView.enter(CmsAppView.java:240) [opencms.jar:11.0.1]
        at org.opencms.ui.apps.CmsAppView.enter(CmsAppView.java:253) [opencms.jar:11.0.1]`

Problem occurs:
- when i edit file

**Comment by dSeidel** [comment]
Hi @filipkratochvil the first error is not that nice, but it is intended. It tells that some formatter configuration has not configured a match. This is a faulty configuration when you want to use it. But, when you create a new one, it's empty in first place since there's not a really good predefined value. Hence for a new formatter configuration the error just tells please configure, in a running system it tells that something is really wrong.
The second error message I cannot reproduce in the current master branch. Looks more like a problem with the index than with the property resource bundle. By the way, the property resource bundle is currently the preferred way for localizations.
