### ISSUE TITLE
Tomcat startup Failing in "opencms"  version 10.5.4 web application , says "ERROR org.apache.commons.digester.Digester Begin event threw exception"

### ISSUE THREAD

**Issue by tarun-chaudhary** [alkacon/opencms-core#694]
**** looking for help/guide to resolve the same, Getting the following log trace:**
-----------**

ERROR org.apache.commons.digester.Digester Begin event threw exception
java.lang.ClassNotFoundException: com.abc.opencms.repository.WebdavCmsRepository
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1892)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
	at org.apache.commons.digester.ObjectCreateRule.begin(ObjectCreateRule.java:210)
	at org.apache.commons.digester.Rule.begin(Rule.java:177)
	at org.apache.commons.digester.Digester.startElement(Digester.java:1583)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.commons.digester.Digester.parse(Digester.java:1892)
	at org.opencms.configuration.CmsConfigurationManager.loadXmlConfiguration(CmsConfigurationManager.java:657)
	at org.opencms.configuration.CmsConfigurationManager.loadXmlConfiguration(CmsConfigurationManager.java:379)
	at org.opencms.main.OpenCmsCore.initConfiguration(OpenCmsCore.java:1189)
	at org.opencms.main.OpenCmsCore.initContext(OpenCmsCore.java:1541)
	at org.opencms.main.OpenCmsCore.upgradeRunlevel(OpenCmsCore.java:2097)
	at org.opencms.main.OpenCmsListener.contextInitialized(OpenCmsListener.java:85)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5110)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5633)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1694)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1684)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

--------------------
The following critical error occurred:
Critical error during OpenCms initialization: Unable to read the OpenCms XML configuration.
Giving up, unable to start OpenCms.
--------------------
ERROR org.opencms.main.OpenCmsCore Critical error during OpenCms initialization: Unable to read the OpenCms XML configuration.
org.opencms.main.CmsException: Critical error during OpenCms initialization: Unable to read the OpenCms XML configuration.
	at org.opencms.main.OpenCmsCore.setErrorCondition(OpenCmsCore.java:370)
	at org.opencms.main.CmsInitException.setErrorCondition(CmsInitException.java:113)
	at org.opencms.main.CmsInitException.<init>(CmsInitException.java:84)
	at org.opencms.main.OpenCmsCore.initConfiguration(OpenCmsCore.java:1191)
	at org.opencms.main.OpenCmsCore.initContext(OpenCmsCore.java:1541)
	at org.opencms.main.OpenCmsCore.upgradeRunlevel(OpenCmsCore.java:2097)
	at org.opencms.main.OpenCmsListener.contextInitialized(OpenCmsListener.java:85)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5110)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5633)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1694)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1684)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
ERROR org.opencms.main.OpenCmsListener Critical error during OpenCms initialization: Unable to read the OpenCms XML configuration.
org.opencms.main.CmsInitException: Critical error during OpenCms initialization: Unable to read the OpenCms XML configuration.
	at org.opencms.main.OpenCmsCore.initConfiguration(OpenCmsCore.java:1191)
	at org.opencms.main.OpenCmsCore.initContext(OpenCmsCore.java:1541)
	at org.opencms.main.OpenCmsCore.upgradeRunlevel(OpenCmsCore.java:2097)
	at org.opencms.main.OpenCmsListener.contextInitialized(OpenCmsListener.java:85)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5110)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5633)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1694)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1684)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.xml.sax.SAXParseException; lineNumber: 148; columnNumber: 90; Error at line 148 char 90: com.abc.opencms.repository.WebdavCmsRepository
	at org.apache.commons.digester.Digester.createSAXException(Digester.java:3363)
	at org.apache.commons.digester.Digester.createSAXException(Digester.java:3389)
	at org.apache.commons.digester.Digester.startElement(Digester.java:1586)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.commons.digester.Digester.parse(Digester.java:1892)
	at org.opencms.configuration.CmsConfigurationManager.loadXmlConfiguration(CmsConfigurationManager.java:657)
	at org.opencms.configuration.CmsConfigurationManager.loadXmlConfiguration(CmsConfigurationManager.java:379)
	at org.opencms.main.OpenCmsCore.initConfiguration(OpenCmsCore.java:1189)
	... 12 more
Caused by: java.lang.ClassNotFoundException: com.abc.opencms.repository.WebdavCmsRepository
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1892)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
	at org.apache.commons.digester.ObjectCreateRule.begin(ObjectCreateRule.java:210)
	at org.apache.commons.digester.Rule.begin(Rule.java:177)
	at org.apache.commons.digester.Digester.startElement(Digester.java:1583)
	... 26 more

**Comment by gWestenberger** [comment]
The class it can't find ( com.abc.opencms.repository.WebdavCmsRepository, which is probably configured somewhere in opencms-importexport.xml ) is not a standard OpenCms class, so it's a configuration issue on your side. You likely took a config file from a different installation without taking the installed libraries into account.
