### ISSUE TITLE
Error while creating resources on the VFS of OpenCms.

### ISSUE THREAD

**Issue by maiconheredes** [alkacon/opencms-core#704]
Server: Tomcat
Database: Oracle

Error while creating resources on the VFS of OpenCms.

org.opencms.db.CmsDbIoException: Error creating the resource "/sites/default/download/sqldeveloper-19.2.1.247.2212-x64.zip".
	at org.opencms.db.CmsDbIoException.createException(CmsDbIoException.java:70)
	at org.opencms.db.CmsDbContext.throwException(CmsDbContext.java:335)
	at org.opencms.db.CmsDbContext.report(CmsDbContext.java:287)
	at org.opencms.db.CmsSecurityManager.createResource(CmsSecurityManager.java:1139)
	at org.opencms.file.types.A_CmsResourceType.createResource(A_CmsResourceType.java:360)
	at org.opencms.file.CmsObject.createResource(CmsObject.java:819)
	at org.opencms.file.CmsObject.createResource(CmsObject.java:870)
	at org.opencms.ade.upload.CmsUploadBean.createSingleResource(CmsUploadBean.java:353)
	at org.opencms.ade.upload.CmsUploadBean.createResources(CmsUploadBean.java:282)
	at org.opencms.ade.upload.CmsUploadBean.start(CmsUploadBean.java:198)
	at org.apache.jsp.WEB_002dINF.jsp.offline.system.workplace.commons.uploadAction_jsp._jspService(uploadAction_jsp.java:119)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:580)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:516)
	at org.opencms.flex.CmsFlexRequestDispatcher.includeExternal(CmsFlexRequestDispatcher.java:191)
	at org.opencms.flex.CmsFlexRequestDispatcher.include(CmsFlexRequestDispatcher.java:165)
	at org.opencms.loader.CmsJspLoader.service(CmsJspLoader.java:654)
	at org.opencms.flex.CmsFlexRequestDispatcher.includeInternalWithCache(CmsFlexRequestDispatcher.java:443)
	at org.opencms.flex.CmsFlexRequestDispatcher.include(CmsFlexRequestDispatcher.java:169)
	at org.opencms.loader.CmsJspLoader.dispatchJsp(CmsJspLoader.java:982)
	at org.opencms.loader.CmsJspLoader.load(CmsJspLoader.java:533)
	at org.opencms.loader.CmsResourceManager.loadResource(CmsResourceManager.java:1196)
	at org.opencms.main.OpenCmsCore.showResource(OpenCmsCore.java:2823)
	at org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:169)
	at org.opencms.main.OpenCmsServlet.doPost(OpenCmsServlet.java:185)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.opencms.jsp.jsonpart.CmsJsonPartFilter.doFilter(CmsJsonPartFilter.java:298)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.opencms.main.OpenCmsUrlServletFilter.doFilter(OpenCmsUrlServletFilter.java:127)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.opencms.db.CmsDbIoException: Error writing data to output stream "b9b6af41-235d-11eb-b578-0208206d3ec4".
	at org.opencms.db.oracle.CmsVfsDriver.internalWriteContent(CmsVfsDriver.java:246)
	at org.opencms.db.oracle.CmsVfsDriver.createContent(CmsVfsDriver.java:83)
	at org.opencms.db.generic.CmsVfsDriver.createResource(CmsVfsDriver.java:786)
	at org.opencms.db.CmsDriverManager.createResource(CmsDriverManager.java:1881)
	at org.opencms.db.CmsDriverManager.createResource(CmsDriverManager.java:2020)
	at org.opencms.db.CmsSecurityManager.createResource(CmsSecurityManager.java:1137)
	... 63 more
Caused by: java.io.IOException: IO Error: Broken pipe
	at oracle.jdbc.driver.OracleBlobOutputStream.write(OracleBlobOutputStream.java:157)
	at org.opencms.db.oracle.CmsVfsDriver.internalWriteContent(CmsVfsDriver.java:225)
	... 68 more
Caused by: java.sql.SQLRecoverableException: IO Error: Broken pipe
	at oracle.jdbc.driver.T4CConnection.putBytes(T4CConnection.java:3094)
	at oracle.sql.BLOB.setBytes(BLOB.java:832)
	at oracle.jdbc.driver.OracleBlobOutputStream.write(OracleBlobOutputStream.java:153)
	... 69 more
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at oracle.net.nt.TimeoutSocketChannel.write(TimeoutSocketChannel.java:215)
	at oracle.net.ns.NSProtocolNIO.writeZeroCopyIO(NSProtocolNIO.java:312)
	at oracle.jdbc.driver.T4CMAREngineNIO.writeZeroCopyIO(T4CMAREngineNIO.java:842)
	at oracle.jdbc.driver.T4C8TTILobd.marshalLobData(T4C8TTILobd.java:171)
	at oracle.jdbc.driver.T4C8TTILob.marshalData(T4C8TTILob.java:704)
	at oracle.jdbc.driver.T4C8TTILob.marshal(T4C8TTILob.java:686)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:250)
	at oracle.jdbc.driver.T4C8TTILob.write(T4C8TTILob.java:176)
	at oracle.jdbc.driver.T4CConnection.putBytes(T4CConnection.java:3088)
	... 71 more

**Comment by aKandzior** [comment]
We have checked this and Oracle support works in our test installation. Since this ticket misses any information about how to reproduce the issue, I will close this now.
