### ISSUE TITLE
User can see, select and (trigger) publish resources in publish dialog even if he is not allow to see them (OpenCms 10.0.1)

### ISSUE THREAD

**Issue by tobias-karrer** [alkacon/opencms-core#709]
### Status Quo
I created a user able to login by adding him to User group
![image](https://user-images.githubusercontent.com/59998109/103930896-5cebff80-5117-11eb-999a-258bd97cc029.png)

and removed permissions for that site
![image](https://user-images.githubusercontent.com/59998109/103931194-d08e0c80-5117-11eb-9bd4-0f3fd4a5d556.png)

User then can open the publish dialog and select resources to publish, even if he is not allowed to see them
![image](https://user-images.githubusercontent.com/59998109/103931473-41352900-5118-11eb-9c68-3b5104db3235.png)

Clicking on publish closes the dialog with message "", but permissions are checked, it got not published and errors are logged:
`...
Caused by: org.opencms.security.CmsPermissionViolationException: Denied access to resource "/sites/group/.content/linkaccordion/", required permissions are "+r".
        at org.opencms.db.CmsSecurityManager.checkPermissions(CmsSecurityManager.java:6967)
        at org.opencms.db.CmsSecurityManager.checkPermissions(CmsSecurityManager.java:6938)
        at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:7338)
        at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:4932)
`

### Expected behaviour
User can't see the resources he has not access in publish dialog.

**Comment by gWestenberger** [comment]
Fixed in master branch.
