### ISSUE TITLE
[OpenCms 12] get error after login

### ISSUE THREAD

**Issue by sinhsac** [alkacon/opencms-core#730]
![image](https://user-images.githubusercontent.com/48815494/140281698-784b652f-c068-42c3-9629-fb9d553148ba.png)

When i login into opencms, it redirect to workplace with error instead of workplace.

**Comment by alkacon-jGraf** [comment]
Is this a manual setup or a docker setup?

**Comment by sinhsac** [comment]
I deploy on 

- Centos 7,
- Oracle JDK 11.0.12,
- 5.7.36 - MySQL Community Server (GPL)
- Apache Tomcat/9.0.54

**Comment by alkacon-jGraf** [comment]
Are there any exceptions thrown in WEB-INF/logs/opencms.log when you log into the workplace?

**Comment by sinhsac** [comment]
There a no error in login process.
but I got some error when start tomcat 
![image](https://user-images.githubusercontent.com/48815494/141035864-bdb971d2-bdad-4337-877b-864609a4adc9.png)
![image](https://user-images.githubusercontent.com/48815494/141035920-d3d6c974-3f6e-4894-85f5-692e34f63afb.png)

**Comment by sinhsac** [comment]
Please see my video for this issues:
the error auto logout.
https://www.youtube.com/watch?v=lD8DkCJ25_M

the error when open list in first time (after install opencms, I think so)
https://www.youtube.com/watch?v=lMu_sG_UXsY

10 Nov 2021 09:06:20,551 [r:5h97F4] ERROR [.ui.apps.lists.CmsResultFacets: 298] Error reading category topic/people. {request_id=5h97F4, request_url=http://my_ip:port/workplace/UIDL/?v-uiId=4} 
org.opencms.file.CmsVfsResourceNotFoundException: Error reading resource from path "/system/categories/topic/".
	at org.opencms.file.CmsVfsResourceNotFoundException.createException(CmsVfsResourceNotFoundException.java:71) ~[opencms.jar:12.0]
	at org.opencms.db.CmsDbContext.throwException(CmsDbContext.java:335) ~[opencms.jar:12.0]
	at org.opencms.db.CmsDbContext.report(CmsDbContext.java:287) ~[opencms.jar:12.0]
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:5154) ~[opencms.jar:12.0]
	at org.opencms.file.CmsObject.readResource(CmsObject.java:3241) ~[opencms.jar:12.0]
	at org.opencms.file.CmsObject.readResource(CmsObject.java:3208) ~[opencms.jar:12.0]
	at org.opencms.relations.CmsCategoryService.getCategory(CmsCategoryService.java:295) ~[opencms.jar:12.0]
	at org.opencms.relations.CmsCategoryService.readCategory(CmsCategoryService.java:587) ~[opencms.jar:12.0]
	at org.opencms.ui.apps.lists.CmsResultFacets.getCategoryLabel(CmsResultFacets.java:279) ~[opencms.jar:12.0]
	at org.opencms.ui.apps.lists.CmsResultFacets.prepareCategoryFacets(CmsResultFacets.java:332) ~[opencms.jar:12.0]
	at org.opencms.ui.apps.lists.CmsResultFacets.displayFacetResult(CmsResultFacets.java:128) ~[opencms.jar:12.0]
	at org.opencms.ui.apps.lists.CmsListManager.executeSearch(CmsListManager.java:2309) ~[opencms.jar:12.0]
	at org.opencms.ui.apps.lists.CmsListManager.search(CmsListManager.java:1777) ~[opencms.jar:12.0]
	at org.opencms.ui.apps.lists.CmsListManager.search(CmsListManager.java:1716) ~[opencms.jar:12.0]
	at org.opencms.ui.apps.lists.CmsListManager.getComponentForState(CmsListManager.java:1838) ~[opencms.jar:12.0]
	at org.opencms.ui.apps.A_CmsWorkplaceApp.openSubView(A_CmsWorkplaceApp.java:308) ~[opencms.jar:12.0]
	at org.opencms.ui.apps.A_CmsWorkplaceApp.onStateChange(A_CmsWorkplaceApp.java:294) ~[opencms.jar:12.0]
	at org.opencms.ui.apps.lists.CmsListManager.onStateChange(CmsListManager.java:1642) ~[opencms.jar:12.0]
	at org.opencms.ui.apps.CmsAppView.enter(CmsAppView.java:240) ~[opencms.jar:12.0]
	at org.opencms.ui.apps.CmsAppView.enter(CmsAppView.java:253) ~[opencms.jar:12.0]
	at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:778) ~[vaadin-server-8.11.2.jar:8.11.2]
	at com.vaadin.navigator.Navigator.lambda$navigateTo$9a874efd$1(Navigator.java:702) ~[vaadin-server-8.11.2.jar:8.11.2]
	at com.vaadin.navigator.ViewBeforeLeaveEvent.navigate(ViewBeforeLeaveEvent.java:54) [vaadin-server-8.11.2.jar:8.11.2]
	at com.vaadin.navigator.View.beforeLeave(View.java:79) [vaadin-server-8.11.2.jar:8.11.2]
	at com.vaadin.navigator.Navigator.runAfterLeaveConfirmation(Navigator.java:730) [vaadin-server-8.11.2.jar:8.11.2]
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:701) [vaadin-server-8.11.2.jar:8.11.2]
	at org.opencms.ui.apps.CmsAppNavigator.navigateTo(CmsAppNavigator.java:65) [opencms.jar:12.0]
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:678) [vaadin-server-8.11.2.jar:8.11.2]
	at org.opencms.ui.apps.CmsAppWorkplaceUi.showApp(CmsAppWorkplaceUi.java:482) [opencms.jar:12.0]
	at org.opencms.ui.actions.CmsDisplayAction.executeAction(CmsDisplayAction.java:76) [opencms.jar:12.0]
	at org.opencms.ui.actions.CmsContextMenuActionItem.executeAction(CmsContextMenuActionItem.java:79) [opencms.jar:12.0]
	at org.opencms.ui.contextmenu.CmsResourceContextMenuBuilder$1.contextMenuItemClicked(CmsResourceContextMenuBuilder.java:153) [opencms.jar:12.0]
	at org.opencms.ui.contextmenu.CmsContextMenu$ContextMenuItem.notifyClickListeners(CmsContextMenu.java:442) [opencms.jar:12.0]
	at org.opencms.ui.contextmenu.CmsContextMenu$1.itemClicked(CmsContextMenu.java:914) [opencms.jar:12.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155) [vaadin-server-8.11.2.jar:8.11.2]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116) [vaadin-server-8.11.2.jar:8.11.2]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445) [vaadin-server-8.11.2.jar:8.11.2]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410) [vaadin-server-8.11.2.jar:8.11.2]
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274) [vaadin-server-8.11.2.jar:8.11.2]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90) [vaadin-server-8.11.2.jar:8.11.2]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) [vaadin-server-8.11.2.jar:8.11.2]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1606) [vaadin-server-8.11.2.jar:8.11.2]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:448) [vaadin-server-8.11.2.jar:8.11.2]
	at org.opencms.main.CmsUIServlet.service(CmsUIServlet.java:352) [opencms.jar:12.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [servlet-api.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [catalina.jar:9.0.54]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.54]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.54]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.54]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.54]
	at org.opencms.main.OpenCmsUrlServletFilter.doFilter(OpenCmsUrlServletFilter.java:150) [opencms.jar:12.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.54]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.54]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [catalina.jar:9.0.54]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:9.0.54]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) [catalina.jar:9.0.54]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [catalina.jar:9.0.54]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.54]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [catalina.jar:9.0.54]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:9.0.54]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [catalina.jar:9.0.54]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [tomcat-coyote.jar:9.0.54]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.54]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895) [tomcat-coyote.jar:9.0.54]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722) [tomcat-coyote.jar:9.0.54]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.54]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:9.0.54]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:9.0.54]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.54]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.opencms.file.CmsVfsResourceNotFoundException: Unable to read resource "/system/categories/topic".
	at org.opencms.db.generic.CmsVfsDriver.readResource(CmsVfsDriver.java:2388) ~[opencms.jar:12.0]
	at org.opencms.db.CmsDriverManager.readResource(CmsDriverManager.java:7893) ~[opencms.jar:12.0]
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:7624) ~[opencms.jar:12.0]
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:5152) ~[opencms.jar:12.0]
	... 70 more

**Comment by alkacon-jGraf** [comment]
Thanks for the bug report. We will investigate the issue.

**Comment by gWestenberger** [comment]
Can't reproduce the issue.
