### ISSUE TITLE
[OpenCms 13] - Issue After upgrading OpenCms 10.5.4 to 13 -opencms.search.solr.CmsSolrIndex:571 - java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by rgaviras** [alkacon/opencms-core#739]
After Upgrade from OpenCms 10.5.4 to versión 13 We have some errors, that we have no explation…

As I show, we have a resource on VFS

 
![image](https://user-images.githubusercontent.com/1841474/169250677-92d4434b-5be1-4d3d-9e01-d575dc8ae27d.png)

Using Sorce Seaqrch tool, It is posible to find it

![image](https://user-images.githubusercontent.com/1841474/169250749-7b023c1f-8f5b-4c5a-8e58-591f01490155.png)

But trough galleries the resource is not shown:

![image](https://user-images.githubusercontent.com/1841474/169250770-018739b7-195f-4a77-85cf-5a778926839b.png)
![image](https://user-images.githubusercontent.com/1841474/169250823-96479027-fd98-4514-9da8-f8b5690cf557.png)
![image](https://user-images.githubusercontent.com/1841474/169250871-a76b8587-b848-4c5f-b7a8-aef4b6189881.png)

At Source code it seems to be ok:
![image](https://user-images.githubusercontent.com/1841474/169250909-47ac159c-835a-4dee-ac55-5e4cc89558a9.png)
![image](https://user-images.githubusercontent.com/1841474/169250928-6aa67d49-0d1e-4712-9eda-d2d1ad1fd368.png)

 

 

We found an error when Editing the resource (/.content/sgeventcalendarjson/sgeventcalendarjson-00001.html) :

_19 May 2022 09:24:26,899 [r:0Kqjud] ERROR [encms.search.solr.CmsSolrIndex: 571] null {cms_project=Offline, cms_siteroot=/sites/ayto-lalaguna, request_id=0Kqjud, request_url=http://opencms.pre.cristobal.local/system/workplace/editors/acacia/editor.jsp?resource=/.content/sgeventcalendarjson/sgeventcalendarjson-00001.html&backlink=https%3A%2F%2Fopencms.pre.cristobal.local%2Fworkplace%23%21explorer%2F4c100b02-85e7-11e9-abfb-934e891b81e7%21%21%2Fsites%2Fayto-lalaguna%21%21%2F.content%2Fsgeventcalendarjson%2F%21%21}
java.lang.NullPointerException: null
        at org.opencms.search.solr.CmsSolrIndex.getDocument(CmsSolrIndex.java:562) [opencms.jar:13.0]
        at org.opencms.search.galleries.CmsGallerySearch.searchById(CmsGallerySearch.java:171) [opencms.jar:13.0]
        at org.opencms.search.galleries.CmsGallerySearch.searchById(CmsGallerySearch.java:78) [opencms.jar:13.0]
        at org.opencms.ade.contenteditor.CmsContentService.readContentDefinition(CmsContentService.java:2191) [opencms.jar:13.0]
        at org.opencms.ade.contenteditor.CmsContentService.prefetch(CmsContentService.java:734) [opencms.jar:13.0]
        at org.opencms.ade.contenteditor.CmsContentService.prefetch(CmsContentService.java:406) [opencms.jar:13.0]
        at org.opencms.ade.contenteditor.CmsContentEditorActionElement.getPrefetch(CmsContentEditorActionElement.java:134) [opencms.jar:13.0]
        at org.opencms.ade.contenteditor.CmsContentEditorActionElement.exportAll(CmsContentEditorActionElement.java:89) [opencms.jar:13.0]
        at org.apache.jsp.WEB_002dINF.jsp.offline.system.workplace.editors.acacia.editor_jsp._jspService(editor_jsp.java:127) [ROOT/:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [tomcat8-jasper-8.5.39.jar:8.5.39]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat8-servlet-api.jar:?]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476) [tomcat8-jasper-8.5.39.jar:8.5.39]
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386) [tomcat8-jasper-8.5.39.jar:8.5.39]
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330) [tomcat8-jasper-8.5.39.jar:8.5.39]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat8-servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:64) [log4j-web-2.17.1.jar:2.17.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:591) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:527) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.opencms.flex.CmsFlexRequestDispatcher.includeExternal(CmsFlexRequestDispatcher.java:191) [opencms.jar:13.0]
        at org.opencms.flex.CmsFlexRequestDispatcher.include(CmsFlexRequestDispatcher.java:165) [opencms.jar:13.0]
        at org.opencms.loader.CmsJspLoader.service(CmsJspLoader.java:665) [opencms.jar:13.0]
        at org.opencms.flex.CmsFlexRequestDispatcher.includeInternalWithCache(CmsFlexRequestDispatcher.java:444) [opencms.jar:13.0]
        at org.opencms.flex.CmsFlexRequestDispatcher.include(CmsFlexRequestDispatcher.java:169) [opencms.jar:13.0]
        at org.opencms.loader.CmsJspLoader.dispatchJsp(CmsJspLoader.java:993) [opencms.jar:13.0]
        at org.opencms.loader.CmsJspLoader.load(CmsJspLoader.java:544) [opencms.jar:13.0]
        at org.opencms.loader.CmsResourceManager.loadResource(CmsResourceManager.java:1194) [opencms.jar:13.0]
        at org.opencms.main.OpenCmsCore.showResource(OpenCmsCore.java:2227) [opencms.jar:13.0]
        at org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:325) [opencms.jar:13.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) [tomcat8-servlet-api.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat8-servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat8-websocket-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.opencms.jsp.jsonpart.CmsJsonPartFilter.doFilter(CmsJsonPartFilter.java:298) [opencms.jar:13.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:64) [log4j-web-2.17.1.jar:2.17.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.opencms.main.OpenCmsUrlServletFilter.doFilter(OpenCmsUrlServletFilter.java:145) [opencms.jar:13.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.17.1.jar:2.17.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat8-catalina-8.5.39.jar:8.5.39]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) [tomcat8-coyote-8.5.39.jar:8.5.39]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat8-coyote-8.5.39.jar:8.5.39]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat8-coyote-8.5.39.jar:8.5.39]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat8-coyote-8.5.39.jar:8.5.39]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat8-coyote-8.5.39.jar:8.5.39]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat8-util-8.5.39.jar:8.5.39]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]_

This error happens always when we create a resource, edit, reindex…

Any Clue… Sombody experience the same…

Thanks in advance!

**Comment by mEmmerich** [comment]
You said that you updated an existing OpenCms 10 installation to OpenCms 13. Please do the following:

1) Delete all subfolders of the /WEB-INF/index folder
2) Delete the WEB-INF/solr folder and rename WEB-INF/solr-update to WEB-INF/solr
Please note: If you have modifed something in the WEB-INF/solr settings on your old installation you must redo them in the new version
3) Open the opencms-seach.xml and make sure that solr is enabled as the wizard disables it before the update.
4) Restart OpenCms and rebuild all search indexes

Those steps are required as the solr version was updated between OpenCms 10 and 13.

Kind regards,
Michael

**Comment by rgaviras** [comment]
Ok, I try.
Thanks

**Comment by rgaviras** [comment]
It works. 

Thanks
