### ISSUE TITLE
Issue on accessing bookmark from shared into site context

### ISSUE THREAD

**Issue by SandrineProusteau** [alkacon/opencms-core#761]
Reproduced in OpenCms 13 and 14

Go in Shared context on a Shared folder and mark it as Bookmark.
Switch to site context, open Bookmarks. The pined folder is displayed. Try to click on it to be redirected to this folder context. It open a error popin : 

```
18 Apr 2023 08:56:41,876 [r:94QAYs] ERROR [pencms.ui.apps.CmsFileExplorer:1585] Error reading resource from path "/shared/shared". {request_id=94QAYs, request_url=https://back.int.intranets.arkema.eurelis.info/workplace/UIDL/?v-uiId=5} 
org.opencms.file.CmsVfsResourceNotFoundException: Error reading resource from path "/shared/shared".
	at org.opencms.file.CmsVfsResourceNotFoundException.createException(CmsVfsResourceNotFoundException.java:71) ~[opencms.jar:13.0]
	at org.opencms.db.CmsDbContext.throwException(CmsDbContext.java:335) ~[opencms.jar:13.0]
	at org.opencms.db.CmsDbContext.report(CmsDbContext.java:287) ~[opencms.jar:13.0]
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:5158) ~[opencms.jar:13.0]
	at org.opencms.file.CmsObject.readResource(CmsObject.java:3241) ~[opencms.jar:13.0]
	at org.opencms.ui.apps.CmsFileExplorer.readTreeLevel(CmsFileExplorer.java:1576) ~[opencms.jar:13.0]
	at org.opencms.ui.apps.CmsFileExplorer$TreeExpandListener.nodeExpand(CmsFileExplorer.java:303) ~[opencms.jar:13.0]
	at jdk.internal.reflect.GeneratedMethodAccessor145.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:706) ~[vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:399) ~[vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:363) ~[vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1190) ~[vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.v7.ui.Tree.fireExpandEvent(Tree.java:1127) ~[vaadin-compatibility-server-8.14.3.jar:8.14.3]
	at com.vaadin.v7.ui.Tree.expandItem(Tree.java:353) ~[vaadin-compatibility-server-8.14.3.jar:8.14.3]
	at com.vaadin.v7.ui.Tree.expandItem(Tree.java:317) ~[vaadin-compatibility-server-8.14.3.jar:8.14.3]
	at org.opencms.ui.apps.CmsFileExplorer.openPath(CmsFileExplorer.java:1514) ~[opencms.jar:13.0]
	at org.opencms.ui.apps.CmsFileExplorer.onStateChange(CmsFileExplorer.java:1080) ~[opencms.jar:13.0]
	at org.opencms.ui.apps.CmsAppView.enter(CmsAppView.java:240) ~[opencms.jar:13.0]
	at org.opencms.ui.apps.CmsAppView.enter(CmsAppView.java:253) ~[opencms.jar:13.0]
	at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:778) ~[vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.navigator.Navigator.lambda$navigateTo$9a874efd$1(Navigator.java:702) ~[vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.navigator.ViewBeforeLeaveEvent.navigate(ViewBeforeLeaveEvent.java:54) ~[vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.navigator.View.beforeLeave(View.java:79) ~[vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.navigator.Navigator.runAfterLeaveConfirmation(Navigator.java:730) ~[vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:701) ~[vaadin-server-8.14.3.jar:8.14.3]
	at org.opencms.ui.apps.CmsAppNavigator.navigateTo(CmsAppNavigator.java:65) ~[opencms.jar:13.0]
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:678) ~[vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.navigator.Navigator$UriFragmentManager.lambda$setNavigator$567eee34$1(Navigator.java:209) ~[vaadin-server-8.14.3.jar:8.14.3]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:706) [vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:399) [vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:363) [vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.server.Page.fireEvent(Page.java:723) [vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.server.Page.updateLocation(Page.java:1158) [vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.ui.UI$1.popstate(UI.java:201) [vaadin-server-8.14.3.jar:8.14.3]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155) [vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116) [vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:442) [vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:407) [vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:275) [vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) [vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1637) [vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:464) [vaadin-server-8.14.3.jar:8.14.3]
	at org.opencms.main.CmsUIServlet.service(CmsUIServlet.java:352) [opencms.jar:13.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) [servlet-api.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [catalina.jar:9.0.67]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.67]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.67]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.67]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.67]
	at org.opencms.main.OpenCmsUrlServletFilter.doFilter(OpenCmsUrlServletFilter.java:150) [opencms.jar:13.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.67]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.67]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.17.1.jar:2.17.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.67]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.67]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [catalina.jar:9.0.67]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:9.0.67]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.67]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [catalina.jar:9.0.67]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.67]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [catalina.jar:9.0.67]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:9.0.67]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) [catalina.jar:9.0.67]
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:433) [tomcat-coyote.jar:9.0.67]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.67]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-coyote.jar:9.0.67]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789) [tomcat-coyote.jar:9.0.67]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.67]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:9.0.67]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:9.0.67]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.67]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.opencms.file.CmsVfsResourceNotFoundException: Unable to read resource "/shared/shared".
	at org.opencms.db.generic.CmsVfsDriver.readResource(CmsVfsDriver.java:2388) ~[opencms.jar:13.0]
	at org.opencms.ocee.cache.CmsVfsCache.readResource(CmsVfsCache.java:863) ~[org.opencms.ocee.base.jar:?]
	at org.opencms.db.CmsDriverManager.readResource(CmsDriverManager.java:7926) ~[opencms.jar:13.0]
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:7628) ~[opencms.jar:13.0]
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:5156) ~[opencms.jar:13.0]
	... 79 more
```

The reverse is working well. Site's bookmarks are accessible from Shared context.

**Comment by gWestenberger** [comment]
This is already fixed in the master branch (commit 9826390747401c28e5e8e3c1eec377931add0451).
