### ISSUE TITLE
Class RawImageInputStream NoClassDefFoundError

### ISSUE THREAD

**Issue by alfonsordm** [alkacon/opencms-core#766]
Hi,

I have installed Opencm15 in Tomcat 9 with Java 11. 

When i try open gallery images and the images (with param "__scale") not show and launch:

java.lang.NoClassDefFoundError: com/github/jaiimageio/stream/RawImageInputStream
        at com.github.jaiimageio.impl.plugins.raw.RawImageReaderSpi.canDecodeInput(RawImageReaderSpi.java:98) ~[jai-imageio-core-1.4.0.jar:1.4.0]
        at javax.imageio.ImageIO$CanDecodeInputFilter.filter(ImageIO.java:571) ~[?:?]
        at javax.imageio.spi.FilterIterator.advance(ServiceRegistry.java:876) ~[?:?]
        at javax.imageio.spi.FilterIterator.<init>(ServiceRegistry.java:870) ~[?:?]
        at javax.imageio.spi.ServiceRegistry.getServiceProviders(ServiceRegistry.java:518) ~[?:?]
        at javax.imageio.ImageIO.getImageReaders(ImageIO.java:652) ~[?:?]
        at javax.imageio.ImageIO.read(ImageIO.java:1458) ~[?:?]
        at javax.imageio.ImageIO.read(ImageIO.java:1363) ~[?:?]
        at com.alkacon.simapi.Simapi.read(Simapi.java:340) ~[alkacon-simapi-1.0.4.jar:1.0.4]
        at com.alkacon.simapi.Simapi.read(Simapi.java:312) ~[alkacon-simapi-1.0.4.jar:1.0.4]
        at org.opencms.loader.CmsImageScaler.scaleImage(CmsImageScaler.java:1191) ~[opencms.jar:15.0]
        at org.opencms.loader.CmsImageScaler.scaleImage(CmsImageScaler.java:1356) ~[opencms.jar:15.0]
        at org.opencms.loader.CmsImageScaler.scaleImage(CmsImageScaler.java:1368) ~[opencms.jar:15.0]
        at org.opencms.loader.CmsImageLoader.getScaledImage(CmsImageLoader.java:319) ~[opencms.jar:15.0]
        at org.opencms.loader.CmsImageLoader.load(CmsImageLoader.java:371) ~[opencms.jar:15.0]
        at org.opencms.loader.CmsResourceManager.loadResource(CmsResourceManager.java:1194) ~[opencms.jar:15.0]
        at org.opencms.main.OpenCmsCore.showResource(OpenCmsCore.java:2287) [opencms.jar:15.0]
        at org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:363) [opencms.jar:15.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) [tomcat-servlet-4.0-api.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-4.0-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
        at org.opencms.jsp.jsonpart.CmsJsonPartFilter.doFilter(CmsJsonPartFilter.java:298) [opencms.jar:15.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
        at org.opencms.main.OpenCmsUrlServletFilter.doFilter(OpenCmsUrlServletFilter.java:150) [opencms.jar:15.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.17.1.jar:2.17.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.36]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.36]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.36]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.36]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.36]
        at psiprobe.Tomcat90AgentValve.invoke(Tomcat90AgentValve.java:38) [psi-probe-tomcat9-3.5.8.jar:3.5.8]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.36]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [catalina.jar:9.0.36]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.36]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.36]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:370) [tomcat-coyote.jar:9.0.36]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.36]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.36]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591) [tomcat-coyote.jar:9.0.36]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.36]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.36]
        at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by alfonsordm** [comment]
https://github.com/jai-imageio/jai-imageio-core/issues/47

Copy jai-imageio-core-1.4.0.jar to Tomcat lib folder.
